### ISSUE TITLE
Consider bringing back pre-transform validation

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#1013]
Before #984 we ran an addition pre-transform validation hook before e.g., fully expanding imports or resolving. It seems that with that approach we were able to handle sources with errors much faster. Now the corresponding validator is folded into the regular validator which runs late, after the AST is fully formed, see https://github.com/zeek/spicy/issues/1009#issuecomment-925809426.

While writing these validators for incomplete ASTs is tricky, providing feedback quickly can be very beneficial e.g., during parser development, or speed up our test suite which contains a larger sample of faulty code. We should consider bringing back some for of pre-transform validation.

**Comment by rsmmr** [comment]
Done.
