### ISSUE TITLE
Request support for windows

### ISSUE THREAD

**Issue by deadash** [zeek/spicy#1053]
This is a great tool, can it support compilation and use on windows?

**Comment by rsmmr** [comment]
There shouldn't be anything fundamental preventing Spicy from working on Windows (it's just generating C++ code in the end) but we haven't look into that yet. There are couple of platform-specific parts around the JIT/dynamic loading that would be need to be ported, and I'm guesxsing there're a few more places in the code where things won't directly compile right now, but nothing major.

I'll close this ticket but if want to talk more (or might even be interested in helping port it?), happy to chat more on Slack.
