### ISSUE TITLE
Transitive includes not handled correctly

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#1057]
Under certain setups imports of imported modules are not implicitly imported. It is important that this works 😅.

```.console
$ tail *.spicy
==> a.spicy <==
module a;

import spicy;

%byte-order=spicy::ByteOrder::Little;

public type A = unit {};

==> b.spicy <==
module b;

import a;
import spicy; # FIXME(bbannier): This should be implicit when importing `a`.

public type B = unit {
    a_: a::A;
};

==> c.spicy <==
module c;
import b;

==> d.spicy <==
module d;

import c;
```

When compiling both `c` and `d` this fails:

```.console
spicyc c.spicy d.spicy -j
/private/var/folders/ht/vtb0rkbd4ws15vx02xdb84zw0000gn/T/d_dc75e53109471175-38c9e38328e44a4.cc:13:58: error: no member named 'a' in namespace '__hlt'
        std::optional<::hilti::rt::ValueReference<__hlt::a::A>> a_{};
                                                  ~~~~~~~^
```

As marked in the source for `b.spicy` there also seems to be an issue of `a` correctly exporting its dependency on `spicy`.

**Comment by bbannier** [comment]
@rsmmr tagging this for spicy-1.4 since I suspect the #984 might have played into this.

**Comment by rsmmr** [comment]
Got fix for the C++ issue.

What's marked with `FIXME` is intentional: Spicy doesn't transitively import modules from the user perspective.

**Comment by bbannier** [comment]
> What's marked with FIXME is intentional: Spicy doesn't transitively import modules from the user perspective.

That's unfortunate as it requires module users to know about all (recursive) dependencies of everything they import, regardless of whether it is visible or used.
