### ISSUE TITLE
`RelWithDebugInfo` build defines `NDEBUG`

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#1058]
A `RelWithDebInfo` build currently does not execute `assert` statements since `NDEBUG` is defined even though one would expect assertions to be checked in a build with debug symbols.

**Comment by rsmmr** [comment]
Oh, I actually didn't realize it should check assertions in that mode. I'm fine making that change but then I think we should switch to building  `Release` by default (which right now, we don't activate at all iirc).

**Comment by bbannier** [comment]
I probably had a misunderstanding here since even the default CMake `CMAKE_CXX_FLAGS_RELWITHDEBINFO` are `-O2 -g -DNDEBUG` so we would be in line with that. What I was looking for was a way to have relatively "production-like" execution times while still checking asserts. I can inject additional flags for that, so there is no change needed here and I am closing this.
