### ISSUE TITLE
Units cannot have sink fields which take parameters

### ISSUE THREAD

**Issue by keithjjones** [zeek/spicy#1063]
Trying this:

```
public type Someunit = unit(arg1: string, arg2: string) {
    len: uint32;
    payload: bytes &size=self.len -> self.AnotherUnit;
    sink AnotherUnit(arg1, arg2);
};
```

gives an error such as this on the `sink AnotherUnit(arg1, arg2)` line above:

```
analyzer.spicy:148:13: syntax error, unexpected '(', expecting attribute or ';'
```

**Comment by bbannier** [comment]
It looks like the error you are hitting is in parsing the Spicy sources. I am not sure whether can support sinks types with parameters easily, but this should at the minimum reported with a good error message instead of just failing like now.

**Comment by rsmmr** [comment]
Yeah, that syntax doesn't work, but you should be able to do this differently:

```
public type Someunit = unit(arg1: string, arg2: string) {
    on %init {
        self.other.connect(new AnotherUnit(arg1, arg2));
    }

    len: uint32;
    payload: bytes &size=self.len -> self.AnotherUnit;

    sink other;
};
```

(Sinks are a bit inconsistent in how they are used.)

**Comment by keithjjones** [comment]
This fix compiles for me.  Thanks @rsmmr !  If this is the intended way to use sinks with parameters, maybe the fix is to put this logic in the documentation?  Not sure I could have figured this out without your help.

**Comment by rsmmr** [comment]
Yeah, it is intended. The idiom to use `new` is there in the docs for sinks. What seems missing is showing somewhere that `new` can be used with unit parameters.
