### ISSUE TITLE
Parse error from sink propagates to connected unit

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#1076]
Given the following code

```.ruby
module test;

type S = unit {
    x : /A/;
};

public type X = unit {
    : bytes &eod { self.s.write($$); }
    sink s;

    on %init { self.s.connect(new S); }
};
```

we can successfully forward data from `X` into `S`.

```.console
$ echo 'A' | spicy-driver test.spicy  -d
$ echo $?
0
```

If however parsing in the sink fails, we will fail even the outer unit
```.console
$ echo '1' | spicy-driver test.spicy  -d
[error] terminating with uncaught exception of type spicy::rt::ParseError: parse error: failed to match regular expression (test.spicy:4:9)
$ echo $?
1
```

This seems to be counter to the expected decoupling a `sink` should provide.

**Comment by rsmmr** [comment]
Yep, that seems unexpected, I think it's a bug.

That said, I'm wondering what we'd *like* to happen here: we don't want top-level parsing to abort, but ideally there'd still be some way to learn about problems. Could we perhaps trigger %error handlers in the parent, but without subsequent abort?

**Comment by bbannier** [comment]
> That said, I'm wondering what we'd like to happen here: we don't want top-level parsing to abort, but ideally there'd still be some way to learn about problems. Could we perhaps trigger %error handlers in the parent, but without subsequent abort?

`X::%error` doesn't look like the right spot to me (wrong unit), and I feel we do not have enough an understanding of where error handling should be going overall (feaatures like e.g., catching of parse errors) to change the semantics of `%error` so it does n.

The implementor of `X` could still add a handler for `S::%error` to get information about failures in `S` and take action, e.g.,

```.ruby
on S::%error {
    throw "error in S";
}
```

All this would need would be to prevent the parse error from propagating out of `S`.
