### ISSUE TITLE
Spicy installation artifacts are huge

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#1092]
Currently our installation artifacts are huge (e.g., around 600MB once installed on debian-10). This is due to us producing artifacts in `RelWithDebInfo` mode with unstripped artifacts. While debug symbols are useful for debugging issues, they also lead to e.g., artificially large installations which can be undesirable if e.g., installations are deployed as containers.

We should consider producing artifacts without debug symbols instead.

**Comment by keithjjones** [comment]
Yes, please.  I have a spicy analyzer that was 300MB in size and after I ran the strip command it was 10MB.  If we could run the cmake strip command during the build we could do this for everyone, but I don't know how to do that.

**Comment by keithjjones** [comment]
The native strip command on a mac is:

```
strip -ru yourfile.htlo
```

while in Linux it is:

```
strip -s yourfile.htlo
```
