### ISSUE TITLE
Lookahead parsing prefers longest instead of shortest match

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#1114]
Given the following unit

```.ruby
module x;

public type X = unit {
	switch {
		-> a: /A/;
		-> b: /ABC/;
	};

	rest: bytes &eod;

	on %done { print self; }
};
```

the generated lookahead parsing seems to prefer to match the longest, not the shortest match,

```.console
$ printf 'ABC' | spicy-driver x.spicy
[$a=(not set), $b=b"ABC", $rest=b""]
```

I see this behavior also if using incremental parsing with chunks with `size=1`.

**Comment by bbannier** [comment]
At least for this reproducer involving regexps, this is due to the behavior of `RegExp` (which in this case is a pretty thin wrapper around jrx). This fails:

```.cpp
auto re = RegExp(std::vector<std::string>{"A{#1}", "ABC{#2}"});
CHECK_EQ(re.match("ABC"_b), 1);
```

**Comment by bbannier** [comment]
Assigning to you @rsmmr since you are the justrx expert.

**Comment by rsmmr** [comment]
So I finally found the context/history for this: this was a deliberate switch a while ago because of unintuitive semantics that using the shortest match introduced. Here's the commit message (from the old development code base before the code went public on GitHub):

```
commit e949eacf6bd2b75236f0c5fd2ede713bfb24c3fd
Author: Robin Sommer <robin@corelight.com>
Date:   Fri Apr 3 06:17:52 2020 +0000

    Fix ill-defined incremental matching of regular expressions.

    Spicy's semantics for matching regex' used to be "take the first
    match" rather than "take the longest match". Turns out that's not
    working well. First, the implementation had trouble with incremantel
    matching in thie model: Dependign on how data came it, for a regex
    like it "a.*" it would stop matching at different points during the
    ".*" part.

    That could have been fixed, but "first match" also just gives weird
    semantics for typical use cases. For example, if we match a typical
    token in a text-baed protocol through "[^ \t\r\n]+", we really don't
    want to stop right after the first character.

    So this commit switches over to searching for the longest match --
    which in many cases, due to the bug, we already did anyways. It also
    fixes how the matching determines whether it's seeing the last chunk
    of input: For streams, it looks at the freezing state. For bytes, it
    takes an additional "is_final" flag. The latter is done through a new
    new match-state overload of advance() for bytes.

commit 1691e2998ace75d00ebee01b7c9cc44532c6d481
Author: Robin Sommer <robin@corelight.com>
Date:   Fri Apr 3 06:18:06 2020 +0000

    Remove &first_match.

    Per the previous commit, the &first_match attribute isn't really
    helpful, we now completely remove it.

```

**Comment by rsmmr** [comment]
So, no bug there. Now I'm wondering what synchronization should do. @bbannier please remind me: are we just following normal look-ahead parsing there currently (and hence take longest match); or are we taking (or are trying to take) the shortest match?

**Comment by bbannier** [comment]
> are we just following normal look-ahead parsing there currently (and hence take longest match); or are we taking (or are trying to take) the shortest match?

It is the first one, we follow usual lookahead semantics here (in fact, it uses the exact same code path). This means that if there are multiple lookahead symbols which can match on synchronization, we would prefer to match potentially later in the stream. If normal lookahead works the same way this seems intuitive to me since users would already have structured their grammar in a matching manner anyway for usual parsing.

**Comment by rsmmr** [comment]
Yeah, I think I agree. A question though: we have a test in `types/unit/synchronize-match-length.spicy` that says: `Checks that we always synchronize on the shortest possible match.`. Isn't that contradicting the look-ahead semantics?

**Comment by bbannier** [comment]
> A question though: we have a test in `types/unit/synchronize-match-length.spicy` that says: `Checks that we always synchronize on the shortest possible match.`. Isn't that contradicting the look-ahead semantics?

I think the comments reflect our original intention, not the actual behavior (it would have been better if a TODO had called this out). Looking at the baseline, we do indeed synchronize on the longest possible match (for input `ABC` we prefer to synchronize on `/A.*/` instead of `ABC`). I'll submit a patch to update the comments.

**Comment by rsmmr** [comment]
Closing this, everything works as we want.
