### ISSUE TITLE
time_ns cannot use variable as an argument

### ISSUE THREAD

**Issue by ynadji** [zeek/spicy#1123]
See minimal example below. If a literal is used (commenting out first two lines of `Bar` and uncommenting the last line) it compiles fine.

```ruby
module Foo;

import spicy;

public function Bar(): time {
  local secs: uint64 = 173281732132132;
  return time_ns(secs);
  #return time_ns(173281732132132);
}
```

```
$ spicy-build -o foo foo.spicy
[error] foo.spicy:7:18: syntax error, unexpected identifier, expecting unsigned integer value or '+'
[error] spicyc: parse error

$ spicy-config --version
1.4.0-dev.174 (b64af90e)
```

**Comment by rsmmr** [comment]
This is on purpose, but I admit that it's confusing. The idea is that `time(<int>)` actually *is* the Spicy literal for a constant time value, so it doesn't allow expressions inside the parentheses. But yeah, it looks like a function call / dynamic constructor, which makes it confusing. 

We should improve this. think we either need to change the syntax for literals, or make the case of expressions work. Applies to a couple of other types as well.

**Comment by ynadji** [comment]
Okay, that makes sense. I'd throw a +1 for making expressions work. My current use case requires some post-processing where I cannot parse all the data in a `unit` and would like to make `time` objects from `uint`s I've "parsed."
