### ISSUE TITLE
path to command line tools in Mac for spicy-driver

### ISSUE THREAD

**Issue by ProfCodeGen** [zeek/spicy#1146]
I downloaded the latest stable for BigSur (https://github.com/zeek/spicy/releases/download/v1.3.0/spicy_macos_big_sur.tar.gz). The issue is that it uses /Library/Developer/CommandLineTools/usr/bin/c++ instead of /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin to find the compilers.

If I put a symbolic link in /Library/Developer/CommandLineTools/usr/bin, then the environment is wrong to find the include files.
Is there a way to specify an alternate path? The help doesn't seem to say so.

**Comment by bbannier** [comment]
Have you installed the Xcode command line tools? This is typically done through

```
$ xcode-select --install
```

**Comment by ProfCodeGen** [comment]
That worked.
I had installed them before, but it looks like that particular path weas removed by an xcode version upgrade, even though
the compiler was invokable from the command line.
