### ISSUE TITLE
generated hlto file permissions are 711 (-rwx--x--x)

### ISSUE THREAD

**Issue by mmguero** [zeek/spicy#1150]
This issue cropped up with the latest release of Spicy (v1.4.0) on Debian Linux 64-bit. I'm using [my own dockerfile](https://github.com/mmguero/zeek-docker/blob/main/base.Dockerfile) to reproduce it but I imagine it would be similar on other environments installing the official Zeek and Spicy release debs.

To illustrate the issue:

Run a docker container with Zeek 4.2.0 and Spicy 1.4.0 and verify my umask isn't weird:

```bash
$ docker run -t -i --rm --entrypoint=/bin/bash ghcr.io/mmguero/zeek:latest
.root 914eea642877 ~> umask 
0022
```

Install any spicy package.

```bash
.root 914eea642877 ~> zkg install --force --skiptests spicy-http
Installing "zeek/zeek/spicy-http"..........................
Installed "zeek/zeek/spicy-http" (v0.0.1)
Loaded "zeek/zeek/spicy-http"
```

Look at the permissions of the hlto files:

```bash
.root 914eea642877 ~> find / -name "*.hlto" -exec ls -l "{}" \;
-rwx--x--x 1 root root 29463088 Mar 15 21:11 /opt/zeek/lib/zeek/plugins/packages/spicy-http/http.hlto
-rwx--x--x 1 root root 29463088 Mar 15 21:11 /opt/zeek/var/lib/zkg/clones/package/spicy-http/build/spicy-modules/http.hlto
```

You'll notice they're `-rwx--x--x` (711) instead of (I would imagine) `-rw-r--r--` (644). This causes non-root users to be unable to run zeek as the htlo files fail with permission errors.

**Comment by bbannier** [comment]
Confirming this is a regression which appeared with e1be41c069e4dd2ea21c79fd07fbeea5bdd7cdbd.
