### ISSUE TITLE
Integer cast returns incorrect type

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#1174]
I would expect that this sample prints `int8`:

```ruby
module foo;

function f(i: int8) { print("int8"); }
function f(i: int16) { print("int16"); }

f(cast<int8>(1));
```

Instead it prints `int16`.

Looking at the generated C++ code this is due to `cast<int8>` creating an `int16`, not the requested `int8`,

```cpp
extern void __hlt::foo::__init_module() {
    f(::hilti::rt::integer::safe<int16_t>(::hilti::rt::integer::safe<std::uint64_t>{1U}));
}
```

**Comment by rsmmr** [comment]
I'm wondering if this is on purpose. I remember issues with using `int8_t` at some places because of it being equivalent to `char` for C++ overload resolution.

**Comment by bbannier** [comment]
This is a regression introduced with #984.
