### ISSUE TITLE
Building libhilti as part of zeek fails with "no space left on device"

### ISSUE THREAD

**Issue by mircsicz** [zeek/spicy#1216]
Hi all,

I'm trying to build zeek from source and keep stumbling over the following issue:

/usr/bin/ranlib: ../../lib/libhilti.a: No space left on device

    [ 36%] Linking CXX executable ../../bin/hilti-config
    make[3]: Leaving directory '/opt/zeek/build'
    [ 36%] Built target hilti-config
    make[3]: Entering directory '/opt/zeek/build'
    make[3]: Leaving directory '/opt/zeek/build'
    make[3]: Entering directory '/opt/zeek/build'
    [ 36%] Linking CXX static library ../../lib/libhilti.a
    /usr/bin/ranlib: ../../lib/libhilti.a: No space left on device
    make[3]: *** [auxil/spicy/spicy/hilti/toolchain/CMakeFiles/hilti.dir/build.make:280: auxil/spicy/spicy/lib/libhilti.a] Error 1
    make[3]: *** Deleting file 'auxil/spicy/spicy/lib/libhilti.a'
    make[3]: Leaving directory '/opt/zeek/build'
    make[2]: *** [CMakeFiles/Makefile2:5040: auxil/spicy/spicy/hilti/toolchain/CMakeFiles/hilti.dir/all] Error 2
    make[2]: Leaving directory '/opt/zeek/build'
    make[1]: *** [Makefile:163: all] Error 2
    make[1]: Leaving directory '/opt/zeek/build'
    make: *** [Makefile:15: all] Error 2

Filesystem seems to have plenty of space:

    Filesystem                         Size  Used Avail Use% Mounted on
    /dev/mapper/ubuntu--vg-ubuntu--lv  9.8G  2.8G  6.5G  31% /
    /dev/mapper/ubuntu--vg-opt         7.9G  5.6G  2.0G  74% /opt

I'm grateful for any hint you can give...

**Comment by bbannier** [comment]
I am wondering whether the build attempts to write a file which exceeds the free space (i.e., a file >2GB here). Could you check whether you still see the error if you attach a larger disk to the system for your build dir?

**Comment by mircsicz** [comment]
OK, just added a 32G HDD to the VM

**Comment by mircsicz** [comment]
THX, didn't expect it to use 22Gs of storage for the whole thing...

**Comment by mircsicz** [comment]
Didn't use an flags... All just straight forward:

    sudo apt-get install cmake make gcc g++ flex bison libpcap-dev libssl-dev python3 python3-dev swig zlib1g-dev
    sudo apt-get install python3-git python3-semantic-version

    git clone --recursive https://github.com/zeek/zeek

    ./configure
    make
