### ISSUE TITLE
C++ keywords as identifiers generates invalid code

### ISSUE THREAD

**Issue by simeonmiteff** [zeek/spicy#1235]
The following C++ keywords are permitted by `spicyc` but cause it to generate C++ code that won't compile:

`alignas`, `alignof`, `_Pragma`, `thread_local`, `true`, `typedef`, `typeid`, `typename`, `union`, `unsigned`, `using`, `virtual`, `volatile`, `wchar_t`, `xor_eq`, `xor`

I have not checked other things a C++ compiler might choke on: types, macros, functions and identifiers that may end up in scope in the same code that stuff from the spicy universe is exposed.

**Comment by rsmmr** [comment]
Actually there's a separate list for C++-level keywords: https://github.com/zeek/spicy/blob/9445f040f915cf87d5f969dec6ceb14bf22fb617/hilti/toolchain/src/compiler/cxx/elements.cc#L26
