### ISSUE TITLE
Wish list: support unit field parsing %error hook to enable customization of error messages

### ISSUE THREAD

**Issue by simeonmiteff** [zeek/spicy#1239]
I'm using the `&requires` unit field hook to constrain parsing. When it fails, zeek emits a `weird.log` entry with `$name` which looks like this: `packet analyzer: &requires failed (/build/specific/path/to/analyzer.spicy:X:Y)`, where X and Y are the line/column of the unit `&requires` hook that trigger the parsing failure.

I think it would be nice to be able to customise these error messages on a per-field basis. I can catch the error '%error' unit hook but: the context of _which_ field failed to parse is lost.

This issue is thus an enhancement request to add support for `on %error` and `on %error(msg: string)` as a unit field hook.

**Comment by rsmmr** [comment]
Also, we have https://github.com/zeek/spicy-plugin/pull/104 pending. I need to revisit that but I believe generally Spicy errors should probably never just end up in `weird.log` automatically, as they just don't fit its style/semantics. I'm thinking to add a `zeek::weird(<string>)` function instead for parsers to trigger Zeek-side weirds as desired. How does that sound?

**Comment by simeonmiteff** [comment]
Talking to @bbannier I've since learned that I have fewer cases than I originally thought where it makes sense to do this (specifically: add a constraint that causes a parse error that I could generate a more meaningful error message, i.e: a `weird.log` entry), but still (probably) a non-zero number of such cases.

I have found _some_ ability to do this on a unit level. Let's say I have this:

```
type TLV = unit {
  tlv_type: uint8;
  tlv_len: uint8;

  switch (self.tlv_type) {
    # ...
    1 -> foo: bytes &size=8; &requires=(self.tlv_len==8);
    # ...
  }
  
  on %errror(msg: string) {
    throw "problem parsing TLV %d" % self.tlv_type;
  }
}
```

The rationale for using `&requires` on the `foo` field is that the length is fixed (let's say, due to the protocol specification), and thus a mismatch between the expected length for the given type and the provided length would cause not only a garbage value for `foo` if it did parse, but also mess up the offsets for subsequent TLV units in the stream (unless I figure out how to do error recovery, maybe?).

Without the `throw` in the unit `%error` hook, a violation of  the `&requires` constraint would generate a parse error with a message in `weird.log` like this: `packet analyzer: &requires failed (/path/to/analyzer.spicy:<row A>:<col B>)`.

By doing the `throw`, that `weird.log` entry becomes: `packet analyzer: problem parsing TLV 1 (/path/to/analyzer.spicy:<row C>:<col D>)`. This loses the line number context but `problem parsing TLV 1` is at least a more useful message than `&requires failed`.

The enhancement request for supporting "field-level semantic validation" (whether that be a field-level error hook, or `raise()` as @bbannier discusses in https://github.com/zeek/spicy/discussions/616#discussioncomment-237601) would allow improving this message to `problem parsing the "foo" TLV: value length of 42 instead of 8` for example.

@rsmmr so having `zeek::weird()` and also sending parse errors to a separate log would advance my objective of customising parse error messages, because I could then replace the `throw` with something like: `zeek::weird("problem parsing TLV %d" % self.tlv_type);` and then not care about the parse error (because it wouldn't pollute `weird.log`) and the `weird.log` entry wouldn't have the `(/path/to/analyzer.spicy:<row C>:<col D>)` bit, which makes it easier to write PCAP+zeek driven `btest` cases without having to normalize logs for `btest-diff` (yes - this is super lame, see below).

On the other hand (unless I misunderstand), relying on `zeek::weird()` would tie the parser to `zeek` library module, which works for analyzers loaded into zeek but not for custom host applications, or more crucially `spicy-driver` and `spicy-dump`, which makes unit testing much harder (which is a trap I've already stepped: I used `&cxxname` to call a C++ function which is itself a wrapper for `zeek::UID` C++ class, and then discovering that I can't link this with `spicyc` because there isn't relocatable bits of zeek to link - hence the PCAP+zeek+btest against `weird.log` shenanigans above).

For now I'm going to back out my `zeek::UID` C++ stuff and rework my test cases to avoid needing to diff against `weird.log`. I think the prerequisites for above use case is captured well in #616 and since this little essay will be referenced there, I'll close this issue now.
