### ISSUE TITLE
Support parsing of `bytes` with `&until` of optional sequence

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#1249]
I am trying to extract a `bytes` until a potentially multi-byte pattern is seen or up to EOD, i.e., the delimiter is optional. This seems harder than needed

- it seems I cannot use a regexp since we do not support negative lookahead, e.g., `x: /(?!MY_DELIM)*/` is not supported
- I cannot use `x: bytes &until=DELIM` and recover from the EOD error since the field will only get updated once `DELIM` was seen; it might be possible to on recovery invoke a parser for `bytes` with know `&size` (needs computation of `&size` and probably also an arbitrary sync point following the `bytes` field, e.g., `: b"" &synchronize`). 
- with multi-byte patterns for `DELIM` one could extract a list of single `bytes` and accumulate the full data on the side. One would then need to strip the `DELIM` from the accumulated data again and reset the input position

I believe we might have all the pieces in place to allow combining `[&until|&until-including]` and `&eod` which is currently not allowed. We should check whether we can enable this in some form or another for all container types.

**Comment by rsmmr** [comment]
> I believe we might have all the pieces in place to allow combining `[&until|&until-including]` and `&eod` which is currently not allowed. We should check whether we can enable this in some form or another for all container types.

Yeah, that sounds right to me, too.
