### ISSUE TITLE
`bytes::[lower|upper]` can fail in undocumented ways

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#1251]
We currently provide `lower` and `upper` methods for `bytes`. These methods take some encoding and will fail with an exception if a given `bytes` does not conform to it.  We should at the very least document this, and possibly improve this API.

It seems weird that for methods from `bytes` to `bytes` we should fail here; the failure would seem more natural to me if they returned a `string`. We could also consider moving the methods into `string` altogether so they cannot fail (but `decode` to get the the `string` would fail). If `bytes` provided a way to sanitize an input for decoding users could even work around this, e.g., with a method which for a given encoding replaces unrepresentable subsequences with a user-provided input. The downside of this is that it would still allow users to generate strings which again cannot be decoded.

**Comment by stevesmoot** [comment]
As the complainer - I'd prefer "do your best job" i.e. if an escape sequence doesnt work out, just go back to looking for lowers to upper (or the reverse for lower()).  Generating strings would be vexing as the library support for them is weaker than bytes (and as mentioned it just moves the problem, tho at least it moves it to a place where an 'API' that exposes errors will make more sense.

in case it helps, my use case was just
if ( b"KEYWORD" in self.field.upper()) 
as a shortcut to see if I needed to dig into field.
(oversimplified, multiple keywords with different following parsing...but it can all move to a regexp)

**Comment by rsmmr** [comment]
I'm thinking we could go the Python route and provide an option to choose the method for failure handling:
https://docs.python.org/3/library/codecs.html#error-handlers. We could offer equivalents for at least `strict`/`ignore`/`replace`, and do that for all methods taking a charset parameter.
