### ISSUE TITLE
Make it possible to use unbundled dependencies

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#127]
Currently we hardcode paths to dependencies (which are all bundled ATM), e.g., when including headers. This makes it hard to build with these dependencies unbundled without patching the code itself.

For header-only dependencies we should at the least use generic paths when including headers, e.g., `hlohmann-json/json.hpp` instead of `hilti/3rdparty/nlohmann-json/json.hpp`.

**Comment by rsmmr** [comment]
#502 comes with reworking the layout for 3rdparty code. For stuff that's used only internally, we don't use any `3rdparty` include paths anymore, it's all done in CMake-land. For includes that are part of the public runtime headers, we continue to use `3rdparty` paths and we install the necessary pieces along with the HILTI/Spicy headers. We could move that over to CMake as well, but I'm not sure that's really better. The paths make clear what's going on, and I don't think we want to have these unbundled anyways. If a distribution insists on doing it differently, we can revisit, but for now I'm closing this.
