### ISSUE TITLE
problem about spicy doc of bitfield

### ISSUE THREAD

**Issue by AatroxMercer** [zeek/spicy#1298]
https://docs.zeek.org/projects/spicy/en/latest/programming/parsing.html?highlight=bitfield#bitfield

In the first paragraph, it says bits 3 to 5 as f.x3 and I don't get it. 
Why is it not bits 3 to 4 as f.x3 so it follows the numbers diven in the code as f.x2 does?

In the next example, \41 should be 0100 0001, so I suppose x1 get 0001 and x2 get 0100, but the result is x2 is equal to 2. 
It seems a little counterintuitive.

I am a liitle confused about the use of bitfield keyword.

**Comment by bbannier** [comment]
Thank you for the ticket @AatroxMercer!

> In the first paragraph, it says bits 3 to 5 as f.x3 and I don't get it.
Why is it not bits 3 to 4 as f.x3 so it follows the numbers diven in the code as f.x2 does?

They should be, this is a typo.

While looking into this I came across a validation issue which I filed separately, #1299.

**Comment by AatroxMercer** [comment]
Thank you for solve my first problem.

But I am still confused about the sencond example.
Should not x1 get the last 4 bits and x2 get the first 4 bits so the result would be x2 = 4 and  x1 = 1?
I reproduce the example in terminal and it does output the same result as the example.

>

**Comment by rsmmr** [comment]
> But I am still confused about the sencond example. Should not x1 get the last 4 bits and x2 get the first 4 bits so the result would be x2 = 4 and x1 = 1? 

I believe the confusion is coming from the use of `\41`: that's octal, not hex. That value in hex is `0201`, and now you're reasoning works: x1 gets the 0x01, and x2 gets 0x02. 

It's using octal just because that happens to be portable with `printf`, but I admit that this example isn't great, I'll make a edit pass over the section.
