### ISSUE TITLE
Unhelpful error when typo in unit name for hooks

### ISSUE THREAD

**Issue by awelzel** [zeek/spicy#1316]
I renamed one of my units and started getting errors of the form:
```
[error] ./unknown-self.spicy:8:8: unknown ID 'self'
```
It took me longer than I want to admit to figure out that the problem was that `on UnitName::%done` should be changed to `on NewUnitName::%done`.

Here's the example within the container:
```
module Test;

public type MagicUnit = unit {
  chunk: bytes &chunked &eod;
};

on MagikUnit::%done {
  if ( self.chunk == b"b" )
    print "yes";
}

root@7d84d55f9217:/src# spicy-driver --version
spicy-driver v1.6.0-dev.133 (1d9ebe9a)
root@7d84d55f9217:/src# spicy-driver ./unknown-self.spicy 
[error] ./unknown-self.spicy:8:8: unknown ID 'self'
[error] spicy-driver: aborting after errors
```

**Comment by awelzel** [comment]
Hmm, piggy backing, the following isn't right (I think just `MagicUnit::chunk { }` is proper), but the error messages for that are the same and unclear what the error is.
```
on MagicUnit::chunk::%done {
}
```

**Comment by rsmmr** [comment]
Yeah, not great. I think it's because it can't resolve the part in front of the `%done`; and because of that missing then can't create a mapping for `self`. And we probably check for `self` not resolving before reporting the original problem.
