### ISSUE TITLE
var &default using unit parameter gives empty value

### ISSUE THREAD

**Issue by awelzel** [zeek/spicy#1319]
Hey - I'm probably doing something unusual/unexpected, but the behavior was surprising, so reporting here.

When defaulting to a unit parameter, the default stays empty (?) rather then the unit parameter's value at the time of instantiation. This is probably not something that should work, but maybe it should error out then.

```
root@7d84d55f9217:/src# cat default.spicy 
module Test;

public type X = unit {
  a: /[A-Z]/;
  b: Y(self.a);
  on %done {
    print "d", self.b.d;
    print "self", self;
  }
};

type Y = unit(a: bytes) {
  c: /[A-Z]/;
  var d: bytes &default=a;
};
root@7d84d55f9217:/src# echo -n "AB" | spicy-driver ./default.spicy 
d, 
self, [$a=b"A", $b=[$c=b"B", $d=b""]]
```
($d is empty instead of "A")

**Comment by bbannier** [comment]
Currently unit variables require manual initialization in e.g., `%init`, so what you are trying here is unsupported. That being said, I wonder whether we shouldn't allow initializing them where they are declared, e.g., via simple assignment or via `&default`. Until we support that we should reject unsupported attributes on unit variable declarations.

**Comment by awelzel** [comment]
After more chatting with @bbannier , seems this is more about `&default` on `vars` rather than unit parameters per se:
```
root@7d84d55f9217:/src# cat really.spicy 
module Test;

public type X = unit {
  var vx: bytes &default="really?";
};

global gx:  X;
print gx, gx.vx;
root@7d84d55f9217:/src# echo -n "AB" | spicy-driver ./really.spicy 
[$vx=b""], 
```

**Comment by bbannier** [comment]
I opened #1320 to add validation to reject code with unsupported unit variable attributes.

**Comment by rsmmr** [comment]
Approved the PR, but yeah, we should add support for `&default` and initialization for unit vars. I believe that would just need to be moved over to the HILTI struct that's being generated.
