### ISSUE TITLE
Availability of contexts in sinks

### ISSUE THREAD

**Issue by Mohan-Dhawan** [zeek/spicy#1354]
It seems that contexts are not available in sinks. In a protocol analyzer that is dependent on other analyzers, it is natural to pass byte buffers across the analyzers as writes to a sink, so it would be helpful if %context is maintained within a sink.

**Comment by bbannier** [comment]
Just to document a workaround, one can already today pass contexts created in e.g., the top-level parser down to a sink, e.g.,

```ruby
module foo;

type Ctx = unit {
	a: uint8;
};

public type X = unit {
	%context = Ctx;
	on %init { self.context().a = 42; }
	sink y;
};

type Y = unit(inout ctx: Ctx&) {
	: uint8 { ctx.a = $$; }
};
```

**Comment by bbannier** [comment]
Closing this for now since usefulness of such a feature is unclear. Please feel free to reopen and add more context.
