### ISSUE TITLE
Bytes decode error handling breaks compatibility

### ISSUE THREAD

**Issue by simeonmiteff** [zeek/spicy#1385]
I noticed #1255 broke a zeek analyzer I was working on last year that relied on the old behaviour of `bytes.decode()` (specifically, that non-printable ASCII chars were escaped). This seems natural for my use case.

I understand why the change was good an necessary (without even considering conversion to UTF8), however, none of the `bytes::DecodeErrorStrategy` options provide backward (bug?) compatibility with the old behaviour. This means I'd have to rework the zeek interface of my analyser to pass a `vector<uint8>` to zeek and then convert the resulting `vector of count` in script land to the same kind of string. This seems like a big impact on users for what I understood to be a bug fix.

I have implemented `bytes::DecodeErrorStrategy::ESCAPE` in #1384, which provides that option:
```
module test;

global s: bytes = b"fo\x00o\xff";

print s;
print s.decode(hilti::Charset::ASCII, hilti::DecodeErrorStrategy::IGNORE);
print s.decode(hilti::Charset::ASCII, hilti::DecodeErrorStrategy::REPLACE);
print s.decode(hilti::Charset::ASCII, hilti::DecodeErrorStrategy::ESCAPE);
```

Output:
```shell
$ spicyc -j decode_test.spicy
fo\x00o\xff
foo
fo?o?
fo\x00o\xff
```

I'm uncertain whether all spicy releases are considered unstable w.r.t. the language (behaviour of types, etc) and that it is OK for #1255 to break existing parsers. I put together the draft PR to frame a discussion and feel out whether this is something you'll entertain.

**Comment by bbannier** [comment]
> I'm uncertain whether all spicy releases are considered unstable w.r.t. the language (behaviour of types, etc) and that it is OK for https://github.com/zeek/spicy/pull/1255 to break existing parsers.

We want to allow ourselves to break the API in new minor releases (but not patch releases). Since #1255 was an API-breaking change it was introduced in a new version 1.6.0 and AFAICT not backported to the 1.5.x series which is e.g., shipped with Zeek's 5.0.x LTS release.

**Comment by simeonmiteff** [comment]
> Thanks for flagging this, I think this could be useful.
> 
> > I'm uncertain whether all spicy releases are considered unstable w.r.t. the language (behaviour of types, etc) and that it is OK for #1255 to break existing parsers.
> 
> We want to allow ourselves to break the API in new minor releases (but not patch releases). Since #1255 was an API-breaking change it was introduced in a new version 1.6.0 and AFAICT not backported to the 1.5.x series which is e.g., shipped with Zeek's 5.0.x LTS release.

Thanks for clarifying.

**Comment by simeonmiteff** [comment]
@bbannier looping back to this:

I double checked that implementing this will actually restore the previous behaviour, and it turns out it doesn't: if you pass `f\0x00o` to zeek from spicy and then put it in a record that gets passed to `Log::write()`, then zeek will escape the slash and it becomes `f\\0x00o`.

If I implement a helper C++ function that just iterates over `hilti::rt::Bytes.str().data()` and does `str += *p` (i.e., append the raw bytes into a `std::string`) then it behaves like before.

Consequently, I think we'd need something like `bytes::DecodeErrorStrategy::PERMIT` (the best name I can think of for: _pass through bytes_), but my spidy sense says this is what you're specifically aiming to avoid with the `decode()` function.

If this direction is undesirable then I'll rather abandon my branch, close the issue and rework my analyser to pass `bytes` to zeek and handle the rendering in script-land.

Please let me know what your think.

**Comment by bbannier** [comment]
Thanks for coming back to this.

> I double checked that implementing this will actually restore the previous behaviour, and it turns out it doesn't: if you pass `f\x00o` to zeek from spicy and then put it in a record that gets passed to `Log::write()`, then zeek will escape the slash and it becomes `f\\x00o`.

Yepp, that sounds like it would encode e.g., a NULL byte as the literal string `"\x00"` (length=4 instead of length=1), and then something does additional escaping on the individual bytes.
 
> If I implement a helper C++ function that just iterates over `hilti::rt::Bytes.str().data()` and does `str += *p` (i.e., append the raw bytes into a `std::string`) then it behaves like before.
> 
> Consequently, I think we'd need something like `bytes::DecodeErrorStrategy::PERMIT` (the best name I can think of for: _pass through bytes_), but my spidy sense says this is what you're specifically aiming to avoid with the `decode()` function.
>
> If this direction is undesirable then I'll rather abandon my branch, close the issue and rework my analyser to pass `bytes` to zeek and handle the rendering in script-land.

One motivation certainly is that Spicy `string` values should contain valid UTF8 so one can do stringly operations with them without having to worry too much about encoding issues; Zeek's `string` OTOH comes with less guard rails there and is more like Spicy's `bytes`. Introducing a big escape hatch like a pass-through strategy would potentially expose more issues to downstream users of the decoded values, so if possible we should avoid that; in fact, the patch that changed the behavior was exactly around making this tighter.

If you can successfully implement your inspection on the Zeek side by passing over Spicy `bytes`, I would prefer that.
