### ISSUE TITLE
Add syntax to capture already known range-length of a parent unit

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#139]
> Keeping mindful that one of the goals being that Spicy authors script achieve correct expression of a dissection appropriately defensive against malformed, and especially against malicious content, one of the low-hanging fruit might be syntax that elegantly (perhaps even automatically) captures the already known range-length of a parent unit. When dissecting a length or a relative pointer element, raising exception if that exceeds the already known range of the parent unit, would efficiently increase the defense in a sub-unit. Note that this should not just be an end-length check, since a relative pointer can be negative, and should be range-checked also against the start of the parent unit. The first thought that occurs to me is to at least designate whenever the attribute being accumulated is a length or a relative pointer.

**Comment by rsmmr** [comment]
Closing, please open new ticket if there's a concrete suggestion.
