### ISSUE TITLE
Transient containers are still stored

### ISSUE THREAD

**Issue by rsmmr** [zeek/spicy#1398]
I believe our optimization for transient (i.e., anonymous) containers isn't working: we're still storing all elements.

Preliminary fix in f4158cc, but it changes the semantics a bit, needs discussion.

Also, I think we have prime candidate for a global optimization here: see if the value of parsed container field is accessed anywhere; if not, make it transient even if the grammar author gave it a name.

**Comment by bbannier** [comment]
Currently the optimizer does not perform any optimizations based on control flow. We would need to add something like this to detect dead writes to `$$`, but our AST currently isn't well suited for that (e.g., no cheap, easy way to retrieve all uses of a value).

I think a easier fix might be to just disallow `$$` for anon fields. This could make e.g., using hooks for printf debugging harder, but this could be worked around (e.g., a user could add a level of unit nesting to attach to the lower level which could have named fields).

**Comment by rsmmr** [comment]
Fixed in #1405 .
