### ISSUE TITLE
Consider introducing a string_view-like type for HILTI

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#1415]
For literals in generated code we currently sometimes emit `std::string` temporaries, e.g., on a paths likely hot at runtime for `location` and `error` arguments for `spicy_rt::waitForInput*`. We do not really need an owning string here, but always pay for the runtime cost.

We should consider introducing a non-owning string_view-like class which is emitted e.g., as a `std::string_view`. If we changed the functions mentioned above to use that view instead we might improve runtime perf.

**Comment by rsmmr** [comment]
Good point. I think we can get rid of those locations arguments altogether. But yeah, the error msgs are bit trickier.

**Comment by bbannier** [comment]
I am closing this since with e8d12df1578f46a0657185a8431ea704646da57f we have effectively implemented a solution for emitting owning, heap-allocated `string`s too often.
