### ISSUE TITLE
hello world (i.e. no public unit) appends extra misleading 'spicy-driver: no parsers available'

### ISSUE THREAD

**Issue by duffy-corelight** [zeek/spicy#143]
The resulting executable from spicy-build, appends extra misleading 'spicy-driver: no parsers available' output.
```
1101 /usr/local/etc/tmp$cat hello.spicy
module Test;

print "Hello, world!";

1105 /usr/local/etc/tmp$spicy/build/bin/spicy-build -o hello.06-Apr-2020.exe hello.spicy 

1107 /usr/local/etc/tmp$./hello.06-Apr-2020.exe
Hello, world!
spicy-driver: no parsers available
```

**Comment by rsmmr** [comment]
Turns out this isn't easy to fix because of an ordering issue with how runtime state is initialized. I'll leave as is, not particularly nice but strictly speaking also not incorrect.
