### ISSUE TITLE
Segfault on self-referential unit

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#1460]
The following unit causes a segfault during AST construction:

```ruby
module foo;

type X = unit {
    var x: X;
};
```

The stacktrace points to the failure being during the resolver phase.

**Comment by bbannier** [comment]
The segfault here is a stackoverflow in detecting whether the unit is resolved, https://github.com/zeek/spicy/blob/03d3ead3980357dfcd463b7505623e4b95c5ac68/spicy/toolchain/include/ast/types/unit.h#L186-L189.

**Comment by bbannier** [comment]
It looks like #1462 will fix this.

**Comment by rsmmr** [comment]
Indeed, this is fixed now.
