### ISSUE TITLE
External hook implementation for fields/units and error messages

### ISSUE THREAD

**Issue by awelzel** [zeek/spicy#1465]
@J-Gras found that the package template showed `on Module::Unit { ... }` usages in a comment and fixed it to explicitly use a `::%done` as without that it's not functional: https://github.com/zeek/package-template/commit/c429a20211f0edc8c6d79cd90a7eea7685a8c8a3

Two topics related to that:

1) Should implicit `%done` work for external hooks on units as previously shown in the template, or was that an oversight? For unit fields `%done` is not needed, though that may be mixing different concepts that only on first sight seem related.

2) The error messages produced for hooks that have an extra %done on unit fields or a a missing %done on units ~fields~ are not helpful for diagnosing the issue.

Test files:
```
# test_mod.spicy
module test_mod;

public type Y = unit {
  y: bytes &size=1;
};
public type X = unit {
  x: bytes &size=1;
  y: 
```

```
# test_mod.spicy 
module zee_test_mod;

import test_mod;

# works
on test_mod::X::%done { }

# error: cannot use module 'test_mod' as an ID - could we say `%done` missing, or use `%done` implicitly?
# on test_mod::X { }

# works - is this implicit %done on the field or something else?
on test_mod::X::x { }

# error: unknown ID 'test_mod::X::b' - this is an extra %done where there shouldn't be one.
# on test_mod::X::b::%done { }

# works - is this implicit %done on the field?
on test_mod::X::y { }

# error: unknown ID 'test_mod::X::y' - same as for `::b` but with a unit type.
# on test_mod::X::y::%done { }
```

**Comment by rsmmr** [comment]
> 1. Should implicit `%done` work for external hooks on units as previously shown in the template, or was that an oversight? 

Yes, it's meant to work. I think we ran into this issue before somewhere but looks like we don't track it in a ticket yet.

> a missing %done on units ~fields~ are not helpful for diagnosing the issue.

One clarification: `%done` works only on units, not on unit fields. I guess one could say `%done` is always implicit on fields, but that we don't have `%init` on fields either, so that wouldn't be very consistent. But we can certainly improve error messaging here.
