### ISSUE TITLE
Allow constants in bitfields

### ISSUE THREAD

**Issue by J-Gras** [zeek/spicy#1467]
In a unit one can define constants that can be used for look ahead parsing:
```
type Foo = unit {
  : b"start";
  x: int8;
}
```
It would be nice to have the same ability for bitfields:
```
type Foo = unit {
  x: bitfield(8) {
    : 0..3 = 12;
    b: 4..7;
  };
}
```

**Comment by rsmmr** [comment]
Just to make sure I understand: You want to use the fact that bits `0..3` equal `12`  to decide whether a `Foo` comes next? And this would also mean that `0..3` must always be `12` (look-ahead or not)?

**Comment by J-Gras** [comment]
> Just to make sure I understand: You want to use the fact that bits `0..3` equal `12` to decide whether a `Foo` comes next? And this would also mean that `0..3` must always be `12` (look-ahead or not)?

Exactly 👍 In my current use case, there would be different variants of `Foo` that can be distinguished based on these bits.
