### ISSUE TITLE
Of multiple `&convert` attributes only the first on seems to be used

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#1485]
When using multiple `&convert` attributes it seems only the first one is used, e.g.,

```ruby
module foo;

public type X = unit {
	# Could expect this to be equivalent to `x: bytes &eod &convert=|$$.split(b"F")|;`
	x: bytes &eod &convert=$$.split(b"F") &convert=|$$|;
};
```

```console
# X.x is not 3.
$ printf '\x01F\x02F\x03' | spicy-dump -d /tmp/bla.spicy
bla::X {
  x: [
    \x01
    \x02
    \x03
  ]
}
```

We should either interpret multiple `&convert` attributes, e.g., in a left to right fashion, or reject them.

**Comment by rsmmr** [comment]
Let's reject, trying to chain multiple converts seems too confusing to me.
