### ISSUE TITLE
`spicy-dump --enable-print` is not functional

### ISSUE THREAD

**Issue by J-Gras** [zeek/spicy#1520]
```
module Test;

public type Foo = unit {
	x: uint8;

	on %done {
		print "all done";
	}
};
```
Running the above using `--enable-print` does not print as expected:
```
$ printf '\x0C' | spicy-dump --enable-print test.spicy
Test::Foo {
  x: 12
}
```

**Comment by bbannier** [comment]
I checked all the way back to spicy-1.1.0 (the oldest version I can still compile on my machine), and AFAICT this never worked. We should either implement support for this, or remove the flag.
