### ISSUE TITLE
Spicy 1.9.0-dev.95 ASAN violation

### ISSUE THREAD

**Issue by vpax** [zeek/spicy#1553]
I have an analyzer that when I run it (and have compiled in ASAN) I get the attached violation. The output says it could be a false positive. However, I decided to look for an issue because a string in the output my analyzer generates upon exit had clearly been stepped on, and not by my code, which doesn't touch the string after setting it.

Happy to try things to run this down if helpful.
[spicy-asan-issue.txt](https://github.com/zeek/spicy/files/12754657/spicy-asan-issue.txt)

**Comment by bbannier** [comment]
Thank you for the ticket, this is certainly a weird one. The report seems to complain about code in `spicy::rt::registerParser` called from generated plugin registration code[^1] which appends to a `vector`, https://github.com/zeek/spicy/blob/50e487ca951febfeadce48fe6ae5e8729ef4a7a5/spicy/runtime/include/parser.h#L356

`globalState()` would if needed allocate a `GlobalState` containing a `vector<const Parser*> parsers`, but it should not do anything to it once it was created.

https://github.com/zeek/spicy/blob/50e487ca951febfeadce48fe6ae5e8729ef4a7a5/spicy/runtime/include/global-state.h#L73-L78

It isn't clear to me how any of this would access a container (probably `parsers` in `GlobalState`) out of bounds. Could you dial up what ASAN diagnoses enabling [more detections](https://github.com/google/sanitizers/wiki/AddressSanitizerFlags), e.g.,

```console
export ASAN_OPTIONS=detect_leaks=0:detect_stack_use_after_return=true:detect_invalid_pointer_pairs=1
```

I could also imagine that this could be triggered by a weird setup with e.g., incompatible components (though [ASAN should e.g., by default detect ODR violations](https://github.com/google/sanitizers/wiki/AddressSanitizerFlags#:~:text=detect_odr_violation)). You probably have already excluded that. If not probably something like the following help narrow potential of this down.

- Zeek and `spicyz` were [both build with sanitizer support](https://github.com/google/sanitizers/issues/362); this should behave correctly if you use a build of Zeek with Spicy and `spicyz` bundled. Remove your build directory and build again to be sure.
- make sure exactly one version of Zeek/`spicyz`/`spicy-config` is found in the environment
- configure output from plugin matches expectation for environment (`mkdir build && cd build && cmake ..`)
- make sure all Spicy analyzers loaded by Zeek were built with the exact same versions of Zeek/Spicy
- issue reproduces when turning off all analyzers
- issue reproduces in a isolated environment, e.g., a Docker container with Zeek build with a similar clang version as on your machine

For the last point, the line numbers do not match locations in the stdlib I see on macos-13.5.2 with

```console
$ clang --version
Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: arm64-apple-darwin22.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

I assume you are just using a different update.

[^1]: For `public` units `registerParser` is automatically invoked from the module registration code `__register_module` which in turn is a magic HILTI initialization function passed to `HILTI_PRE_INIT` which gets invoked when Spicy loads a compiled module.

**Comment by vpax** [comment]
> ```export ASAN_OPTIONS=detect_leaks=0:detect_stack_use_after_return=true:detect_invalid_pointer_pairs=1```

That unfortunately doesn't produce any additional diagnostic output.

**Comment by vpax** [comment]
> * Zeek and `spicyz` were [both build with sanitizer support](https://github.com/google/sanitizers/issues/362); this should behave correctly if you use a build of Zeek with Spicy and `spicyz` bundled. Remove your build directory and build again to be sure

I did a full rebuild and yep the problem went away, so I'm closing this. In the process I ran across something puzzling which I'll post in #development . Thanks for the help!
