### ISSUE TITLE
`spicy-build`: Uncaught exception of type hilti::rt::UnsetOptional if input does not align

### ISSUE THREAD

**Issue by J-Gras** [zeek/spicy#1622]
```Spicy
module Test;

import spicy;

type MyPDU = unit {
        x1: uint16;
        x2: uint8;
};

public type PDUs = unit {
        : MyPDU[];
};
```
Using `spicy-build` I see a strange error if I am trying to process input that doesn't align in terms of the number of bytes to be parsed:
```
# spicy-build test.spicy
# printf '\x01\x02\x03' | ./a.out
# printf '\x01\x02' | ./a.out
[error] a.out: terminating with uncaught exception of type hilti::rt::UnsetOptional: unset optional value (test.spicy:5:14-8:2)
```

**Comment by bbannier** [comment]
This error comes about since the input cannot be parsed (requires 3 bytes, only two given). In e.g., `spicy-1.8.2` we instead reported a clearer error:

```
[error] a.out: terminating with uncaught exception of type spicy::rt::ParseError: expecting 1 bytes for unpacking value (bla.spicy:5:13)
```

**Comment by J-Gras** [comment]
Yep, I get that one if I use `spicy-driver`:
```
# printf '\x01\x02' | spicy-driver test.spicy 
[error] terminating with uncaught exception of type spicy::rt::ParseError: expecting 1 bytes for unpacking value (test.spicy:7:6)
```

**Comment by bbannier** [comment]
Actually I see a `ParseError` reported even on `main` (38b13fcdaaf07f6befc56118e55179db2f31ca67). Which version are you running?

**Comment by J-Gras** [comment]
Just tested using latest master `spicyc v1.10.0-dev.50 (e1d38c32)`:
```
# spicy-build test.spicy
# printf '\x01\x02\x03' | ./a.out 
# printf '\x01\x02\x03\x04' | ./a.out
[error] a.out: terminating with uncaught exception of type hilti::rt::UnsetOptional: unset optional value (test.spicy:5:14-8:2)
```

**Comment by bbannier** [comment]
Thanks for checking, it looks like `spicy-build` picked up a Homebrew Spicy installation I also had sitting around. When removing that I see the error on `main` as well. It looks like we first reported `UnsetOptional` instead of `ParseError` with 97498fa8972fbd7d27d897f7364d969723ef0a71.
