### ISSUE TITLE
5th layer packet analyzer

### ISSUE THREAD

**Issue by ortal555** [zeek/spicy#1629]
Could not register a 5th layer packet analyzer to execute after ANALYZER_TCP (also a packet analyzer).
It's seems like the packet does not go to the spicy analyzer although I used the function:
PacketAnalyzer::register_for_ports()
Thanks in advance!

**Comment by rsmmr** [comment]
Would be good to have a full reproducer, otherwise it's hard to understand what's going on. Feel free to reopen if you still have one.
