### ISSUE TITLE
Parsing trailing null byte padding using a regular expression fails to parse

### ISSUE THREAD

**Issue by kkvarfordt** [zeek/spicy#1634]
If the data being parsed contains 0 to 3 bytes of trailing null byte padding and a regular expression is used to parse this data, in certain configurations, the null byte padding fails to get parsed or an infinite parsing loop is entered.  The attached files illustrate this behavior.

Version: `spicy-driver v1.9.0 (7b8eff5)`

=====================
File: `regex_padding.spicy` 
Desc: Spicy code showing trailing null byte padding failing to parse.
Command: `spicy-driver -f spicy_test_two_null_bytes.in regex_padding.spicy`
Result:
```
clang: warning: -lc++abi: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -lc++abi: 'linker' input unused [-Wunused-command-line-argument]
unit2_field_1 => 7 
unit2_field_2 => \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
unit2_field_3 => ~&%\x89\x00\x0b\x00
unit2_field_4 => 
```

===================== 
File: `regex_padding_in_line.spicy`
Desc: Spicy code with Unit2 from the above `regex_padding.spicy` removed and the cooresponding field(s) declared in line of Unit1.  This code works as expected.
Command: `spicy-driver -f spicy_test_two_null_bytes.in regex_padding_in_line.spicy`
Result:
```
clang: warning: -lc++abi: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -lc++abi: 'linker' input unused [-Wunused-command-line-argument]
unit1_field_3 => 7 
unit1_field_4 => \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
unit1_field_5 => ~&%\x89\x00\x0b\x00
unit1_field_6 => \x00\x00
```

=====================
File: `regex_padding_with_sink.spicy` 
Desc: Spicy code similar to the `regex_padding.spicy` code, but with a sink configured.  This code is very close to my actual use case which started my Spicy regex adventure.  This code results in an infinite parsing loop. :-(
Command: `spicy-driver -f spicy_test_two_null_bytes.in regex_padding_with_sink.spicy`
Result:
```
infinite parsing loop
```
Misc Files:
 File | Description |
|--------|--------|
|`spicy_test_no_null_bytes.in` | Test input that contains 0 trailing null bytes |
|`spicy_test_one_null_bytes.in` | Test input that contains 1 trailing null bytes |
|`spicy_test_two_null_bytes.in` | Test input that contains 2 trailing null bytes |
|`spicy_test_three_null_bytes.in` | Test input that contains 3 trailing null bytes |
|`regex_padding-hilti-trace.out` | Hilti trace file from regex_padding.spicy |
|`regex_padding-spicy-verbose.out` | Verbose parsing file from regex_padding.spicy |
|`regex_padding_in_line-hilti-trace.out` | Hilti trace file from regex_padding_in_line.spicy |
|`regex_padding_in_line-spicy-verbose.out` | Verbose parsing file from regex_padding_in_line.spicy |
|`regex_padding_with_sink-hilti-trace.out` | Hilti trace file from regex_padding_with_sink.spicy |
|`regex_padding_with_sink-spicy-verbose.out` | Verbose parsing file from regex_padding_with_sink.spicy |

**Comment by kkvarfordt** [comment]
[code.zip](https://github.com/zeek/spicy/files/13835394/code.zip)

**Comment by rsmmr** [comment]
I've only looked at the first case so far (`regex_padding.spicy`) but there it's seems an issue with the input: the `&size` on `unit1_field_3` does not contain the padding. With the following change it works for me: 

```
@@ -7,7 +7,7 @@

     unit1_field_1 : uint32 &byte-order=spicy::ByteOrder::Little;
     unit1_field_2 : bytes &size=12;
-    unit1_field_3 : Unit2()[] &size=self.unit1_field_1;
+    unit1_field_3 : Unit2()[] &size=self.unit1_field_1 + 2;

     on %error(msg: string) {
         print "###############################";
```

```
# spicy-driver -f spicy_test_two_null_bytes.in regex_padding.spicy
unit2_field_1 => 7
unit2_field_2 => \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
unit2_field_3 => ~&%\x89\x00\x0b\x00
unit2_field_4 => \x00\x00
```

**Comment by kkvarfordt** [comment]
Doh - apologies.  In my efforts to minimize the code it seems I got carried away with the first case (`regex_padding.spicy`).

That being said, I still think there is an issue with the `regex_padding_with_sink.spicy` example.  If you use the `spicy_test_no_null_bytes.in` as input, you still end up in an infinite loop.  Using this data, `unit2_field_3` is set to `&size=71` bytes which lines up with the rest of the data in the input file.

Thanks for looking into this.

**Comment by rsmmr** [comment]
Yeah, I can confirm that there's something odd going on in that `regex_padding_with_sink.spicy` case. I'll look into it.

**Comment by rsmmr** [comment]
@kkvarfordt Can you give #1642 a try?

**Comment by kkvarfordt** [comment]
Can confirm #1642 fixes the `regex_padding_with_sink.spicy` infinite loop.  Thanks.
