### ISSUE TITLE
Allow to access original field value before `&convert`

### ISSUE THREAD

**Issue by J-Gras** [zeek/spicy#1651]
In some situations it could be handy for field hooks to have access to the original value before a `&convert` takes place.

One example I encountered would be parsing a container:
```
type Message = unit {
	a: uint8;
	b: uint8;
};

public type PDUs = unit {
	m: (Message &convert=$$.a)[] &until=(orig-$$.b == 0);
};
```

Another one could be `&requires`:
```
public type PDUs = unit {
	m: Message &convert=$$.a &requires=(orig-$$.b == 23);
};
```

**Comment by J-Gras** [comment]
Just noticed that my original examples are confusing. By `orig-$$` I meant the original `$$` value.

Regarding the workaround, I assume `get_a` should be used in the `&convert`, right?
```ruby
m: (Message &convert=get_a($$, self))[] foreach {
  ...
```
To be honest, instead of using this code, I would rather use a function that loops the container again and does the conversion. That's way easier to follow.

**Comment by bbannier** [comment]
>Regarding the workaround, I assume get_a should be used in the &convert, right?
Yepp, correct, I forgot changing that part of the example.

> To be honest, instead of using this code, I would rather use a function that loops the container again and does the conversion. That's way easier to follow.

If you can store the full vector that's not a bad approach; what I tried here was something as close to `&until` as possible, e.g, not introducing another container or loop over the full data. Re: maintainability, the same argument could be made for a dedicated syntax to refer to the original.

**Comment by rsmmr** [comment]
I'll go ahead and close this as it doesn't seem worth the overhead.
