### ISSUE TITLE
&convert usage makes self.field unavailable within field's %done hook

### ISSUE THREAD

**Issue by awelzel** [zeek/spicy#1661]
A minimal reproducer:
```
module Test;

import spicy;

public type X = unit {
  x: uint8;
  xs: bytes &eod &chunked &convert=(spicy::bytes_to_hexstring($$)) {
    print "$$", $$;
    print "xs", self.xs;
  }
};

$ printf "\x80\x11\x22\x33\x44\x55\x66" | spicy-driver --increment 4 x.spicy
$$, 112233
[error] terminating with uncaught exception of type hilti::rt::UnsetOptional: unset optional value (x.spicy:9:5)
```

If one removes the `&convert` attribute on `xs`, The current `self.xs` value becomes available within the `%done` hook of the field. Seems `&convert` shouldn't have this effect and instead ensure the "converted" value is available in `self.xs`.

---

This came [up in Slack](https://zeekorg.slack.com/archives/C012CQV1K29/p1706120460756419).

I'm looking at raising an event whenever one "chunk" of a `&chunked` field was consumed (think `http_entity_data` style event).

In the `.evt` file I'd like to use:
```
on WebSocket::Frame::chunk -> event websocket_frame_data($conn, $is_orig, self.chunk);
```

And in the grammar, chunk is roughly the following.
```
  chunk: bytes &size=self.payload_len &chunked &convert=unmask(self, $$) {
    zeek::protocol_data_in(zeek::is_orig(), $$);
  }
```

When using `self.chunk` in the `.evt` file, a violation is triggered:
```
unset optional value (analyzer/protocol/websocket/websocket.evt:18)        \x89\x04Zeek
```

A workaround is to assign `self.chunk` to `$$` within the inline `%done` hook before `zeek::protocol_data_in()`.

**Comment by bbannier** [comment]
The issue here seems to be that the parsing with `&chunked` doesn't directly populate `xs` with a value, but this only occurs after the chunked parsing is done.

**Comment by bbannier** [comment]
> Just to make sure this didn't go under, there's no issue if I remove the `&convert`:

Yep, that's the normal population of the value after parsing is done. We might need to trigger then whenever a chunk is processed since we allow users to run hooks at that point.

**Comment by bbannier** [comment]
There are actually more things wrong with chunked parsing. After a field is done parsing in addition to potentially setting the unit field we currently also update offsets, https://github.com/zeek/spicy/blob/daa2e3ce48a92dcf6662df724a8bb1c8d5f8df4b/spicy/toolchain/src/compiler/codegen/parser-builder.cc#L733-L834

```ruby
module Test;

public type X = unit {
    xs: bytes &eod &chunked {
        print self.offset();
    }
};
```

```console
# Use incremental feeding so we get multiple chunks.
$ printf "\x80\x11\x22\x33\x44\x55\x66" | ~/src/spicy/build/bin/spicy-driver -d /private/tmp/bla.spicy -i 1
0
0
0
0
0
0
0
```

I was hoping to call that code after parsing of a chunk is done, but unfortunately we don't seem to have direct access to it from there,

https://github.com/zeek/spicy/blob/daa2e3ce48a92dcf6662df724a8bb1c8d5f8df4b/spicy/toolchain/src/compiler/codegen/parsers/types.cc#L210

**Comment by rsmmr** [comment]
I think we should make '$$' work here and let it refer to the current chunk of bytes, and then generally interpret attributes on  a `&chunked`  field  (like `&convert`) as applicable to the final chunk only, and assign that to the field once we're done.

**Comment by awelzel** [comment]
> I think we should make '$$' work here ..

Yes, `$$` in the `.evt` would solve this.

> ... and let it refer to the current chunk of bytes, and then generally interpret attributes on a &chunked field (like &convert) as applicable to the final chunk only, and assign that to the field once we're done.

`$$` within `.evt` would be the `&convert`ed chunk of bytes? Otherwise, at least for my use-case, it wouldn't really be useful.

**Comment by rsmmr** [comment]
> Yes, `$$` in the `.evt` would solve this.

+1

> `$$` within `.evt` would be the `&convert`ed chunk of bytes? Otherwise, at least for my use-case, it wouldn't really be useful.

No, it would be the current `bytes` value. I believe the converted value would only very rarely be useful (or even meaningful) because it's undefined how the chunking takes place: you could be getting 1 byte or a thousand, and have no control over where things are split. Your `bytes_to_hexstring($$)` is one of the few cases where it could be useful (basically whenever it's just per-byte conversions, not multiple bytes), but couldn't you do that on your end as well? Just call `bytes_to_hexstring($$)` on the received value before passing it on (even inside the EVT)?

**Comment by bbannier** [comment]
@rsmmr `$$` refers to the converted value. Like you wrote, if that makes sense for the user is up to them, e.g., `&convert` does a base64 conversion the results could be wrong (and the fix would be to use a filter).

**Comment by rsmmr** [comment]
> @rsmmr `$$` refers to the converted value. Like you wrote, whether that makes sense for the user is up to them, e.g., if `&convert` does a base64 conversion the results could be wrong (and the proper tool would be to use a filter).

That's my point: I don't think it should refer to the converted value inside a `&chunked` field. In fact, I'd go so far and disallow using `&convert`  on a `&chunked` field altogether.

**Comment by awelzel** [comment]
> Your bytes_to_hexstring($$) is one of the few cases where it could be useful (basically whenever it's just per-byte conversions, not multiple bytes),
> In fact, I'd go so far and disallow using &convert on a &chunked field altogether.

The use-case was per byte xor decoding. But yes, I see now and agree with the proposed exclusion.

Even pondering a bit if `&chunked` fields should be recommended to be anonymous due to not being set until the last chunk (and then only with whatever remained).

`$$` for my use-case in `.evt` won't quite help. Yes, could use `convert($$)` in the .evt, but it's also needed in the `%done` hook of the chunked field (for `zeek::protocol_data_in`) and the decoding is not cheap. Doing convert explicit within `%done` and assigning to a unit variable sounds pragmatic enough now that `&convert` is out of the picture.

**Comment by rsmmr** [comment]
Sounds like conclusion here is to remove support for the combination of `&chunked` and `&convert`. #1703 puts a deprecation in place.
