### ISSUE TITLE
section 5.1.6.1 uses  type `address` everywhere else shows  type `addr` 

### ISSUE THREAD

**Issue by duffy-corelight** [zeek/spicy#168]
5.1.6.1. Address
Spicy parses addresses from either 4 bytes of input for IPv4 addresses, or 16 bytes for IPv6 address. To select the type, a unit field of type `address` must come with either an &ipv4 or &ipv6 attribute.

uses  type `address` in a rectangle box, everywhere else shows  type `addr`

**Comment by rsmmr** [comment]
This has been fixed.

**Comment by duffy-corelight** [comment]
Where https://github.com/zeek/spicy/issues/230 comments that: "As of a page-refresh 28-Apr-2020 on https://dev.corelight.io/docs/spicy/programming/parsing.html#parsing-types, #168 has not yet been fixed" that was inaccurate. It is indeed fixed, on https://docs.zeek.org/projects/spicy/en/latest/programming/parsing.html , but I had been looking at old docs (dev.corelight.io vs docs.zeek.org).
