### ISSUE TITLE
Supporting leading + on integer constants to force signedness

### ISSUE THREAD

**Issue by duffy-corelight** [zeek/spicy#170]
In BACnet, we have had reliable success supporting leading + or - on all signed integer constants to make that explicit, rather than ever having ambiguity between signed / Unsigned decimal constants syntactically. This gives the availability of brevity where a leading + or - signed integer constant is then always a signed constant, and an unadorned one could default to unsigned.

In BACnet it was even practical to require leading + or - on all signed integer constants, since those are rare, to make it explicit, and draw the programmer's attention to the perhaps-unexpected special considerations of the leading 0 signed Integer. In spicy, I don't think we would benefit from making it required, but making it available would be advantageous.

```
module Issue_170_test;

public type addNegativeInt = unit {
# https://dev.corelight.io/docs/spicy/programming/parsing.html#unit-parameters
#
# has a provision that:
# the exact type of the integer constant is important, you should use their constructor
# syntax to make that explicit (e.g., uint32(42), int8(-1); vs. using just 42 or -1).
    var signedOffset: int64;
    on %init {
#      self.signedOffset = int64(6) - int64(+3);
      self.signedOffset = int64(6) - +3;
    }
};
```
shows spicy currently does not support leading + on signed integer constants to make that explicit.
```
1628 /usr/local/etc/tmp/submod$spicy/build/bin/spicyc -j ../Issue_170_explicit_int.spicy
[error] ../Issue_170_explicit_int.spicy:12: operator usage is ambigious: <int<64>> - <uint<64>>
[error] ../Issue_170_explicit_int.spicy:12:   candidates:
[error] ../Issue_170_explicit_int.spicy:12:   - <int<64>> - <int<64>> [hilti::operator_::signed_integer::Difference]
[error] ../Issue_170_explicit_int.spicy:12:   - <uint<64>> - <uint<64>> [hilti::operator_::unsigned_integer::Difference]
[error] spicyc: aborting after errors
```
Uncommenting line 11 produces:
```
1629 /usr/local/etc/tmp/submod$spicy/build/bin/spicyc -j ../Issue_170_explicit_int.spicy
[error] ../Issue_170_explicit_int.spicy:11: syntax error, unexpected '+', expecting
 unsigned integer value or '-'
[error] spicyc: parse error
```

**Comment by rsmmr** [comment]
We actuall have the `+N` syntax, however it's still (and explicitly) producing an unsigned currently. Switching to signed seems to make sense, just need to see if there's anything depending on the current behavior.
