### ISSUE TITLE
Attach %error handlers to unit fields

### ISSUE THREAD

**Issue by sethhall** [zeek/spicy#1824]
I would like to be able to attach %error handler blocks to fields within a unit instead of only the entire unit.  I have a use case for this in a kerberos parser where I'm using `self.backtrack()` to deal with optional fields but I only want to call backtrack on particular field failures but there are other places that the unit could fail that I would like to have "normal" failures.

I would like to be able to write this code...

```
type Int32 = unit(tagged: bool=False, itag: uint8=255) {
   : ASN1::ExplicitTagHeader(itag) if (tagged) %error {
       self.backtrack();
   };

   : ASN1::Tag;
   len: ASN1::Length;
   value: bytes &size=self.len
                &convert=$$.to_int(spicy::ByteOrder::Network)
                &requires=(self.value >= -2147483648 && self.value <= 2147483647);
} &convert=self.value;
```

You can see how the &requires attribute can cause a failure in the unit but in that case I don't want to backtrack.  I only want the backtrack behavior if that first field fails.

**Comment by rsmmr** [comment]
I like this, and I think it should be relatively easy to implement. We can track `%error` like we currently do with `%debug`: as a property on a hook that we query during parser generation. Then, when emitting a field that has an `%error` hook, we just need to wrap it into its own try/catch, like we already do for unit-level `%error` hooks.

**Comment by sethhall** [comment]
Would this cause code generation to create a hook for every field in every unit?  Seems like that could end up ballooning the generated code quite a bit if so.

**Comment by rsmmr** [comment]
No, we just add a try/catch to fields that do have an `%error` handler, with the `catch` executing that handler.

**Comment by sethhall** [comment]
Ah, nice.

**Comment by rsmmr** [comment]
Done by #1838
