### ISSUE TITLE
Runtime Libraries?

### ISSUE THREAD

**Issue by sethhall** [zeek/spicy#1840]
I would like to be able to use externally defined libraries at runtime but I'm *pretty* sure it isn't possible yet, so if I'm right that it isn't possible, I'd like to do a feature request.

Right now it's a little weird to try and build Spicy libraries because anything you build ends up needing to be included at build time which can cause code bloat.

Is it reasonable to want runtime libraries in spicy?  I don't know if it's a problem architecturally.

**Comment by bbannier** [comment]
Is this about using system libraries from custom C++ code (as opposed to "linking" Spicy "libraries")? In that case you can add a library to be linked dynamically (if linking a shared library) by passing it via the [`--cxx-link` flag](https://docs.zeek.org/projects/spicy/en/latest/programming/extending.html#linking-to-libraries).

**Comment by sethhall** [comment]
No, I was really thinking of libraries for commonly parsed data structures.  What really brought this up for me recently was implementing the uLEB128 type...
https://gist.github.com/sethhall/e1dfacc1eb93b0a8dee96b211a8d8428#file-notepad_cache-spicy-L4

I can imagine some structures and utility functions being available as "libraries" but there doesn't seem to be a good way to do it now outside compile-time sharing.

**Comment by sethhall** [comment]
Had a chat with Robin about this and it seems like it's currently not really something that could be put on the table.
