### ISSUE TITLE
Problem with bytes &size=self.offset()

### ISSUE THREAD

**Issue by sethhall** [zeek/spicy#1842]
I'm not sure if this is related to some expression parsing issue in &size attributes on bytes fields or something else, but I'm seeing a weird behavior...

This works as you might expect (parse 3 bytes then calculate the crc32 for those bytes)...
```spicy
module Test;
import spicy;

public type X = unit {
    a: uint8;
    b: uint8;
    c: uint8;
    : bytes &size=3 &parse-at=self.input() {
        self.crc32 = spicy::crc32_add(spicy::crc32_init(), $$);
    }
    var crc32: uint64;
};
```

But this doesn't work (even though `self.offset()` returns 3)...
```spicy
module Test;
import spicy;

public type X = unit {
    a: uint8;
    b: uint8;
    c: uint8;
    : bytes &size=self.offset() &parse-at=self.input() {
        self.crc32 = spicy::crc32_add(spicy::crc32_init(), $$);
    }
    var crc32: uint64;
};
```

It seems that self.offset() used in the &size field ends up returning zero?

**Comment by rsmmr** [comment]
Oh ... Never thought about this but the way `offset()` is currently implemented, means its works only inside hooks, not from attributes. We should fix that.

**Comment by rsmmr** [comment]
It's a different issue actually: it's the `&parse-at` that gets applied before `offset()` is evaluated, meaning offset is now zero indeed. That's not intuitive, fixing.

**Comment by sethhall** [comment]
Ok, that bug is pretty unintuitive. :)
