### ISSUE TITLE
Using a regex parsed bytes value in &requires

### ISSUE THREAD

**Issue by sethhall** [zeek/spicy#1846]
I'm not sure if the title accurately represents what is going on here or not, but I have some examples of what works and what doesn't...

Using a regex parsed unit value to compare against regex group bytes in a &requires doesn't work...
```spicy
module Test;

public type X = unit {
    b: /b/;
    x: /a(b+)c/ &requires=($1 == self.b);
};
```
```sh
❯ printf 'babc' | HILTI_DEBUG=spicy spicy-driver test6.spicy
[error] terminating with uncaught exception of type hilti::rt::IndexError: vector index 1 out of range (test6.spicy:5:8-5:15)
```

But if the value we parse is parsed with a literal, that works fine...
```spicy
module Test;

public type X = unit {
    b: b"b";
    x: /a(b+)c/ &requires=($1 == self.b);
};
```
```sh
❯ printf 'babc' | HILTI_DEBUG=spicy spicy-driver test6.spicy
```

If we do the comparison in a field hook, it also works fine (it just seems to be broken in the &requires comparison)...
```spicy
module Test;

public type X = unit {
    b: /b/;
    x: /a(b+)c/ {
        print ($1 == self.b);
    }
};
```
```sh
❯ printf 'babc' | HILTI_DEBUG=spicy spicy-driver test6.spicy
True
```

**Comment by rsmmr** [comment]
My initial take would be that this is a similar issues to #1842 (some parsing parsing state is available inside the hook, but not yet inside the field's attributes). However, it surprises me that it works with the literal, as that wouldn't make a difference then. Needs more investigation.

**Comment by rsmmr** [comment]
So turns out two things coming together: the main one is a bug with how we extract the data for capture groups. The second is that after regexp matching we aren't immediately trimming the data, whereas for bytes we do. The latter explains the difference for the two cases: the bug only manifests if the data isn't at the beginning of the stream.
