### ISSUE TITLE
Add "#pragma region" to generated C++

### ISSUE THREAD

**Issue by sethhall** [zeek/spicy#1851]
It would be nice to indicate regions of generated C++ code, VScode will show the regions in the small "code map" that's on the right side of your window.  Here is some MS documentation about it: https://learn.microsoft.com/en-us/cpp/preprocessor/region-endregion?view=msvc-170

While playing around I added some regions to generated code, I don't know if these are good or not, but it makes the generated code a little explorable (since the regions are named and can be folded in the editor)...

```
#pragma region Test::X internal parsing
....
#pragma endregion
#pragma region Test::X public API implementation
....
#pragma endregion
#pragma region Test::X public API
....
#pragma endregion
```

**Comment by sethhall** [comment]
It's neat to have the view of the code on the right side of the editor window... <img width="144" alt="Screenshot 2024-09-02 at 9 48 02 PM" src="https://github.com/user-attachments/assets/606601d6-de56-4909-a2f1-f0078aa412d4">

**Comment by rsmmr** [comment]
I'm voting no on this. We already have comments for some readability, and going further with editor-specific markup feels too much to me.
