### ISSUE TITLE
Cannot use unit parameters to specify a literal to parse

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#1859]
When parsing a field one can use e.g., `const` values to specify literals to expect, but using unit parameters in the same place does not resolve, e.g.,

```ruby
module foo;

type X = unit {
    : Y(0);
};

type Y = unit(expected: uint8) {
    : expected;
};
```

```console
$ spicyc -dj foo.spicy
[error] foo.spicy:8:5-8:15: unknown ID 'expected'
[error] spicyc: aborting after errors
```

**Comment by rsmmr** [comment]
The error message isn't great but it's correct to reject this: these constants/literals must be know at compile time, so parameters can't be supported.
