### ISSUE TITLE
Incompatible use of `&max-size` and `&size` on element type not rejected in vector parser

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#1865]
We usually reject incompatible use of attributes, but this validation does not seem to fire for vector element types. Instead the attributes seem to be ignored.

```ruby
module foo;

public type X = unit {
    # a: bytes &size=1 &max-size=4;  # ERROR: attributes cannot be combined: &size, &max-size
    b: (/a{1,3}/ &max-size=4 &size=3)[];
};
```

```console
$ printf 'aaaa' | spicy-dump -d foo.spicy
foo::X {
  b: [
    aaa
    a
  ]
}
```

I would have expected above example to fail, either by being rejected at compile time or by raising a parse error. To be compatible with usual field parsing we should probably implement a validation rejecting this at compile time.

**Comment by evantypanski** [comment]
Note that this does trigger an assertion with debug builds:

```
$ printf 'aaaa' | spicy-dump -d foo.spicy
Assertion failed: (! (field->attributes()->find("&size") && field->attributes()->find("&max-size"))), function preParseField, file parser-builder.cc, line 740.
[1]    45217 done       printf 'aaaa' |
       45218 abort      spicy-dump -d foo.spicy
```

And it's not particular to vectors, it's just "inner fields", so this also applies if you remove the `[]` after the parentheses.
