### ISSUE TITLE
same concept is called `local` inside functions as is called `var` inside units

### ISSUE THREAD

**Issue by duffy-corelight** [zeek/spicy#189]
Same concept is called `local` inside functions as is called `var` inside units. I have found myself frequently changing an existing piece of code from unit to function and vice-versa. That in each such refactor, every local variable needs to have the keyword changed, feels like an unnecessary burden.
```
function IMSI(contentExceptLast: bytes, lastbyte: uint8) {
  local label: string = "\x22";
  for (idx in contentExceptLast) {
    label = label + "%02X" % idx;
  }
  print "%s%02X\x22," % (label, lastbyte);
}
```

**Comment by rsmmr** [comment]
I see "local" and "var" as conceptual different, would rather not unify.

For the semicolon, it's "C-style syntax" once more: function vs type.
