### ISSUE TITLE
Inconsistent EOD handling in parsing of vector of dynamic length

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#1915]
If a grammar does not constrain the size of a vector we generate code for look-ahead parsing. We are however inconsistent in how we treat left over input data after we finish parsing.

Consider the following grammar:

```ruby
module foo1;

public type X = unit {
    a: (b"1")[];
};
```

For this vector parsing we generate look-ahead parsing which expects either `b"1"` or EOD. The remaining `b"2"` in the input is an error since it is not expected by the grammar.

```console
$ printf 1112 | spicy-dump -d foo1.spicy
[fatal error] terminating with uncaught exception of type spicy::rt::ParseError: no expected look-ahead token found (foo.spicy1:4:5-4:16)
```

If a field follows the list we handle this differently.

```ruby
module foo2;

public type X = unit {
    a: (b"1")[];
    b: b"2";
};
```

```console
$ printf 1112____ | spicy-dump -d foo2.spicy
foo2::X {
  a: [
    1
    1
    1
  ]
  b: 2
}
```
In this case for the list we generate lookahead parsing which expects either `b"1"` or `b"2"`. The list then consumes any (possibly zero) `b"1"` and a following `b"2"` is consumed by `X::b`; any remaining input data is silently discarded raising no error.

Naively I would have expected that for the first case we would have also ignored not matching the vector literal, producing a potentially empty list and discarding any leftover input. The current behavior seems to be due to us explicitly expecting EOD instead of just any not-matching literal.

**Comment by rsmmr** [comment]
I can't seem to  reproduce this with `main`:

```
# cat test.spicy
module foo1;

public type X = unit {
    a: (b"1")[];
};

# ./bin/spicy-dump --version
spicy-dump v1.12.0-dev.188 (99049d80d)

# printf 1112 | ./bin/spicy-dump -d test.spicy
foo1::X {
  a: [
    1
    1
    1
  ]
}
```

Which is I think what you would expect. Not sure why this is different for you, can you double-check that you still see this?

**Comment by bbannier** [comment]
Sorry, I checked against an older dev snapshot built as part of Zeek. Bisecting, it looks like this started to work with 2223f18de4a568465f8fbea349237648b8bfbe5a. I agree that the behavior today is what we'd want.

The only potential thing to do here could be to add dedicated test, but we could also close this out.

**Comment by rsmmr** [comment]
> I agree that the behavior today is what we'd want.

As part of https://github.com/zeek/zeek/pull/4015, I have confirmed (and am now testing) that this is also how Zeek is behaving more generally with Spicy parsers: ignore excessive data once parsing is finished. So I think we're good and I'll go ahead and close.
