### ISSUE TITLE
Add option to Spicy driver to read input from file

### ISSUE THREAD

**Issue by duffy-corelight** [zeek/spicy#200]
Support spicy-driver taking a -f argument, where if present spicy would open that as a file, using that command line parameter as the name of a file, and take the stream to parse from there.

**Comment by rsmmr** [comment]
I suggest we do the following for now:

- Add `-f <path>`. let's not support `@` for now, it's easy to do with a shell loop around it.
- Make a function available to Spicy scripts to read environment variables: `getenv(VAR)`. That way, you can pass in a file name that way from an outer script wrapper; and that's a more generally useful capability, too.

**Comment by duffy-corelight** [comment]
I concur. Making a function available to Spicy scripts to read environment variables: getenv(VAR) is sufficient to satisfy this request to have the passed-in file name that way. And is capable of more functionality, and flexibility for the investment, compared to having just the cmd line string.
