### ISSUE TITLE
Catch when time runs into the limits of its value range

### ISSUE THREAD

**Issue by duffy-corelight** [zeek/spicy#228]
to_time() ceases outputting integer number above year 2554 
```
module Issue_228_WrapsTime;
 whatMaximumTime();

function whatMaximumTime() {
  local Year2554: time = b"\x40\x00\x00\x00".to_time(hilti::ByteOrder::Big);
  print "Note: %%X and %%s both output same:";
  print " %%X: %X" % (Year2554,);
  print " %%s: %s" % (Year2554,);
   print "";
   Year2554 = b"\x04\x4B\x80\x00\x00".to_time(hilti::ByteOrder::Big);
  print "x044B800000: %X" % (Year2554,);
   Year2554 = b"\x04\x4B\x90\x00\x00".to_time(hilti::ByteOrder::Big);
  print "x044B900000: %X" % (Year2554,);
   Year2554 = b"\x04\x4B\xC0\x00\x00".to_time(hilti::ByteOrder::Big);
  print "x044BC00000: %X" % (Year2554,);
}
```
outputs
```
spicy/build/bin/spicyc -j Issue_228_to-time_Year_2554.spicy
Note: %%X and %%s both output same:
 %X: 2004-01-10T13:37:04.000000000Z
 %s: 2004-01-10T13:37:04.000000000Z

x044B800000: 2554-07-19T17:23:12.000000000Z
x044B900000: 1970-01-10T21:04:54.290448384Z
x044BC00000: 1970-02-16T06:53:42.290448384Z
```

**Comment by duffy-corelight** [comment]
BTW, since the defined semantics of to_time() are to produce an integer, the better default when applying "%s" %  to the result, should suppress the decimal point and those nine trailing 0's.

**Comment by rsmmr** [comment]
Small correction: `time` is a separate data type, and `to_time` produces that. 

Not sure where the year 2554 limit comes from. 

We should probably add a `strtfime` to add custom date formatting.

**Comment by rsmmr** [comment]
> Not sure where the year 2554 limit comes from.

Ah, that's the max our nanoseconds-in-uint64_t can represent. That seems acceptable, but we should catch overflow.

**Comment by rsmmr** [comment]
So the todo here is:

- Use hilti::rt::integer::safe<uint64_t> for the internal state in `time` and `interval`.

I'll create a separate ticket for strftime().

**Comment by bbannier** [comment]
One possible approach could be to remove the constructor `Time::Time(uint64_t)` so that we always have to go through `Time(hilti::rt::integer::safe<uint64_t>)`. Doing that leads to a number of failed tests for e.g.,`Bytes`, e.g., the following test reduced from `hilti/types/bytes/to-time.hlt` fails,
```
auto t1 = "\001\002\003\004"_b.toTime(ByteOrder::Big);
auto t2 = Time(16909060.000000);
CHECK_EQ(t1, t2);
```
