### ISSUE TITLE
Add library function to print bytes as hex strings

### ISSUE THREAD

**Issue by duffy-corelight** [zeek/spicy#229]
```
module Issue_229_leadingZeroHexadecimalValues;
 leadingZeroHexadecimalValues();

function leadingZeroHexadecimalValues() {
  local acceptable: uint64 = b"36000000000".to_uint();
  print "36000000000 rendered %s0X and %s010X: %0X %010X" % ("%", "%", acceptable, acceptable);
  acceptable = 400;
  print "400 rendered %sX and %s0X: %X %0X" % ("%", "%", acceptable, acceptable);
}
```
shows that %0X is not a specifier which does that.
```
3470 /usr/local/etc/tmp$spicy/build/bin/spicyc -j Issue_229_leadingZeroHexadecimalValues.spicy
36000000000 rendered %0X and %010X: 861C46800 0861C46800
400 rendered %X and %0X: 190 190
```

**Comment by duffy-corelight** [comment]
When bytes picks up a variable length, it will be a common case to want pairs of hexadecimal digits output, irrespective of how long that variable length is. Logic to apply %02X %04X %06X %08X is cumbersome.

**Comment by rsmmr** [comment]
I don't quite get what you're looking for. This is working just a like C-style format string, and `%04X` for example gives me 4 characters with leading zeros filled in, just as I would expect. 

Can you elaborate?

**Comment by duffy-corelight** [comment]
As in the example there shown, output from "%0X" is 861C46800 which the human eye, at that length, will attempt to group from the left, i.e. 86 1C 46 8-oh-this-is-looking-awkward, dang, the whole thing is actually 08 61 C4 68 00. But when the length of the bytes is dynamic, one cannot just always use "%010X" to force the leading 0, since %010X will only work up through 5 bytes. One needs "%012X" for six bytes, "%014X" for seven bytes, etc. What we really need is a format that forces a leading 0 at all lengths.

**Comment by rsmmr** [comment]
This seems to be mixing up two separate things: rendering bytes as hex, and formatting integers. `%X` expects an integer, and that point its clear what size that has (8/16/32/64).

Different suggestion: what if we gave you a function `bytes_as_hex(d: bytes)` that rendered `d` into a string of hex-pairs, e.g.:

```
bytes_as_hex(b`\x01\x23\x45`) -> "012345"
bytes_as_hex(b`\x08\x61\xC4\x68\x00`) -> "0861C46800"
```

We could add a `min_length` parameter to fill up the resulting string to a minimum length by inserting zeros on the left.

(I believe we could actually implement that in Spicy itself through a for-loop over the bytes.)

**Comment by duffy-corelight** [comment]
Yes, a routine to do this is probably the optimal solution. You have captured the essence. The caller does know the length at the moment they need the operation, and a for loop operating on each byte is entirely general enough.

**Comment by JustinAzoff** [comment]
@neslog this looks like what you could have used the other day.

**Comment by duffy-corelight** [comment]
I can foresee that just about as soon as this function becomes available, the need for, or a request for, a version that outputs lowercase letters for the A through F values, will arise.

**Comment by rsmmr** [comment]
Let's call this function `bytes_to_hexstring` for consistency with Zeek. Implementation can be similar; https://github.com/zeek/zeek/blob/master/src/zeek.bif#L2829 (but we can do it in pure Spicy).

We can add an optional argument to switch between lower- and upper case. I'd make lower the default.
