### ISSUE TITLE
Add library function spicy::strftime

### ISSUE THREAD

**Issue by rsmmr** [zeek/spicy#237]
... so that people can customize the formatting of timestamps.

**Comment by duffy-corelight** [comment]
Be sure to use an implementation that includes the %-d et al., which are useful. 
and to avoid nextDate.strftime("%A, %B, %-d"));
being reported as an invalid format string.

As http://strftime.org/ mentions:  
%d	Day of the month as a zero-padded decimal number.	
is widely implemented, but  
%-d	Day of the month as a decimal number. (Platform specific)

strftime initially was created lacking that, but between Python 2 and 3 that became standardized.

**Comment by rsmmr** [comment]
I agree that `%-d` would be useful, but it seems like a pretty rare find among implementations, and I'd prefer just using `std::strftime` to implement this than including a custom implementation. We can then also just link to, say, https://en.cppreference.com/w/cpp/chrono/c/strftime, for documentation.
