### ISSUE TITLE
Add format string validation

### ISSUE THREAD

**Issue by rsmmr** [zeek/spicy#249]
We need to ensure that format strings are used correctly (i.e., the `%` string operator) so that (1) the number of arguments matches the number of format specifiers, and (2) each format specifier is matched up with the a type that actually supports that specific kind. 

This is a bit tricky because we'll need to start parsing the format string ourselves. Right now, we just outsource it all to tinyfmt.

Bonus issue: We could look into swapping out tinyfmt against `{fmt}`.

**Comment by duffy-corelight** [comment]
Does spicy plan to be strict about %lX when passing int64? Strict about %lX or %ulX when passing uint64? Existing examples are using "%X" when passing uint32. Note that our most basic 5.1.1 example
```
public type Foo = unit {
    version: uint32;

    on %done {
        print "0x%x" % self.version;
    }
};
Let’s use spicy-driver to parse 4 bytes of input through this unit:

# printf '\01\02\03\04' | spicy-driver foo.spicy
0x1020304
```
already shows lack of the leading 0 before the 1, because "0x%x" rather than "0x%08x" was specified.

**Comment by bbannier** [comment]
Related #327

**Comment by rsmmr** [comment]
Superseded by #448.
