### ISSUE TITLE
Add pre/post skipping

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#26]
- Spicy
    - Unit properties
        - [ ] %skip-pre, %skip-post

  Old tests in `*.spicy` in https://github.com/rsmmr/hilti/blob/master/tests/spicy/unit/skip-property-disable.spicy and https://github.com/rsmmr/hilti/blob/master/tests/spicy/unit/skip-property.spicy

**Comment by rsmmr** [comment]
I now remember a use case where this is especially helpful: stripping out white space in ASCII protocols/format. And I'm thinking we should expand it to also support an additional `%skip` that skips matching data anywhere between the fields inside a unit. Then a module-level `%skip = [[:space:]]*` can be used to just generally skip all white space. (And  `%skip = Null` inside a unit would turn it off locally.)

**Comment by bbannier** [comment]
I wonder whether these should really take e.g.,  `/[[:space:]]*/` and not instead `/[[:space:]]/`, i.e., expect users to directly specify the data to skip instead of them also having to encode that the data is optional. This could e.g., be useful if we want to allow skip patterns which are not regexps, but also other parseable data.
