### ISSUE TITLE
vector of bytes does not match a filter method; reports call does not match any method: <TheUppercaser::Foo>.__on_x(<bytes>)

### ISSUE THREAD

**Issue by duffy-corelight** [zeek/spicy#271]
vector of bytes seems incompatible with using a filter
```
module Issue_270;

type Filter = unit {
    %filter
    : bytes &eod &chunked { self.forward($$.upper()); }
};

public type Foo = unit {
    on %init { self.connect_filter(new Filter); }
    x: bytes[] &size=1 { print $$; }
    on %done {
      print "\n";
    }
};
```
reports
```
printf "sDeTr\n" | build/bin/spicy-driver /usr/local/etc/tmp/Issue_270_on_x.spicy
[error] /usr/local/etc/tmp/Issue_270_on_x.spicy:10: call does not match any method: <Issue_270::Foo>.__on_x(<bytes>)
[error] /usr/local/etc/tmp/Issue_270_on_x.spicy:10:   candidate methods:
[error] /usr/local/etc/tmp/Issue_270_on_x.spicy:10:   - <Issue_270::Foo>.__on_x(<const vector<bytes>>)
[error] spicy-driver: aborting after errors
```
When trying instead, removing the &size=1, instead reports
```
spicy$        printf "sDeTr\n" | build/bin/spicy-driver /usr/local/etc/tmp/Issue_270_on_x.spicy
Bus error: 10
```

**Comment by rsmmr** [comment]
This is going to be fixed with #284 (update coming there). However, that Spicy code is probably not going to do what you intended: `x: bytes[] &size=1 ` limits the vector to just one bye total, so you'll get a single-element vector, with that element being one byte.

I'm guessing what you meant here is `x: (bytes &size=1)[];` (i.e., associate the size with the elements). #284 will support that as well.

**Comment by duffy-corelight** [comment]
Where you say that Spicy code x: bytes[] &size=1 limits the vector to just one byte total, is that behavior interacting the way we would like, with respect the distinction between &size and &length? Is &size supposed to impose an absolute limit at which the sudden conclusion of the final being-accumulated element of the vector is dictated?

**Comment by duffy-corelight** [comment]
And do we support (or want to support) &size inside parenthesis and another &size outside after the parenthesis?

**Comment by rsmmr** [comment]
Yes `&size` imposes a hard limit on the field, as if it had reached end of data. It works for all types of fields, just happens to be most common with `bytes` (which without any further attributes just greedily parses everything it can).

To specify the length in terms of array size, use `x: bytes[1]`.

And yes, it should now work to have `&size` both inside and outside of the parenthesis at the same time (but I haven't tried it ...)
