### ISSUE TITLE
keyword %invariant that is placed before assert, similar to how %debug is placed before print

### ISSUE THREAD

**Issue by duffy-corelight** [zeek/spicy#285]
Provide a keyword %invariant that is placed before assert, similar to how %debug is placed before clauses or hooks which contains print. %invariant is for expressing those which it is best to always retain, worthy of run-time enforcement always, even in production, as the best place and the best way to abend because later assumptions will also fail, but in a less clear manner. Many debugging sanity checks which will come into existence while crafting and building .spicy scripts, are actual invariants. Giving explicitness to those which are, will help them stay--as they should--when the debugging might later get ripped out or turned off, after the debugging session resolves whatever it was that led to prolific %debug and or special-purpose assert statements peppering the code.

**Comment by duffy-corelight** [comment]
At the moment, I don’t have any particular functional requirement for %invariant to perform, and it is just a syntactic marker, since the assert() which then immediately follows, throws a fatal exception.

**Comment by rsmmr** [comment]
I'm gonna close this. `&requires` now solves some of it, and I don't think I like extending the semantics/interpretation of `assert` like this.  I'll instead add a note #89 that we'll need a way to trigger an explicit `parse error` from inside a hook, just as `&requires` does. If we have that, normal error handling (and in the future: error recovery) can kick in.
