### ISSUE TITLE
Documentation issues (just add to it when you notice something)

### ISSUE THREAD

**Issue by duffy-corelight** [zeek/spicy#309]
collecting place for documentation corrections, each as a comment.

**Comment by duffy-corelight** [comment]
The change in line 27 doc/autogen/types/map.rst in 
[https://github.com/zeek/spicy/commit/3a30e9ad38466589b01dccdd5c0ae337c4978011](url)
should just have eliminated the entry, in favor of the method with exact same signature, documented in the next entry below it, line 31. Eliminate one or the other, keeping either the short description or the long but not both.

**Comment by duffy-corelight** [comment]
And if retaining the long description,
The key must exists, otherwise the operation
 ->
The key must exist, otherwise the operation

**Comment by duffy-corelight** [comment]
If the three DivisionAssign were changed to +=, in https://github.com/zeek/spicy/pull/308/commits/64506900cd526f56d27a4a27911f01f09bfe08db then another correction is needed. += is SumAssign. I presume /= is maybe DivisionAssign though with the use of slash to denote regular expression maybe means something other than /= is the operator that invokes DivisionAssign.

**Comment by rsmmr** [comment]
I just fix the DivisionAssign doc and verified that is parses as intended.

**Comment by rsmmr** [comment]
Add a note on building the Zeek plugin without JIT support so that it won't have any Spicy runtime dependencies. Might fit well into the FAQ.

**Comment by rsmmr** [comment]
Check where `-p` is still needed for the documentation examples.

**Comment by rsmmr** [comment]
Document DPD integration

**Comment by duffy-corelight** [comment]
In section 5.1.2 Unit Hooks
In particular, any field that haven’t been parsed yet, will remain unset. 
 ->
In particular, any field that hasn’t been parsed yet, will remain unset.

**Comment by rsmmr** [comment]
Use #352  now.
