### ISSUE TITLE
suggest handling operators // and //=, even if just to make error reporting meaningful 

### ISSUE THREAD

**Issue by duffy-corelight** [zeek/spicy#310]
Since operators // and //= will be attempted by some authors, since spicy does support /= on real and the more common use-case needs //= when operating on real type variable, it does seem worthwhile to  make the  error reporting meaningful.

I had pasted a script for experimentation, as a comment in the documentation fixup ticket
https://github.com/zeek/spicy/pull/308 to exercise the various manifestations of error reporting, but /= does work and it can be documented as-is. The script there is actually more applicable here in this ticket, rather than there, so I've pasted that short script for experimentation again here, where it rightly belongs.

If making the tokenizer pick up the three characters //= is possible (and if we do adopt that suggestion, then also extend the tokenizer to pick up the two characters // ) that should be done prospectively, even if only to then immediately make a meaningful error report, if those operators are still going to be unsupported.

We would underserve authors if we just leave the obscure triad of ways that parsing fails when it encounters operators // and //=

**Comment by duffy-corelight** [comment]
```
module Issue_308_DivisionAssign;

Foo();

function Foo() {
    local wantShifted: int32 = 234;
      wantShifted /= 10;
      print wantShifted;
      wantShifted /= 10;
#      wantShifted // 10;
# if uncommented reports a quite directive error

#      wantShifted //= 10;
# if uncommented reports a reasonable error
      print wantShifted;
}

public type FooUnit = unit {
    var wantShifted: int32 = 567;
    on %init {
      self.wantShifted /= 10;
      print self.wantShifted;
    }
    on %done {
#      self.wantShifted // 10;
# if uncommented here, reports as DIVIDEASSIGN error, because two lines below contains a slash 

      self.wantShifted /= 10;
#      self.wantShifted //= 10;
# if uncommented reports a reasonable error

#      self.wantShifted // 10;
# if uncommented here, reports obscure errors depending on content of the comment, after the slash
      print self.wantShifted;

# especially since the presence or absence of / in this comment changes what is reported 
    }
};
```

**Comment by rsmmr** [comment]
Not convinced here. Not sure this a commonly enough needed operator to add, and it's seems like a rare enough mistake that I don't want to make the scanner special-case a non-existing operator.
