### ISSUE TITLE
Setting a const equal to a string causes a segfault

### ISSUE THREAD

**Issue by dopheide-esnet** [zeek/spicy#333]
[bgp-const-segfault.tar.gz](https://github.com/zeek/spicy/files/4670607/bgp-const-segfault.tar.gz)

Similar files to issue 61, but in this case resulting in a segfault:
$ zeek -Cr bgp-test.pcap bgp.spicy bgp.evt bgp.zeek
Segmentation fault: 11

**Comment by rsmmr** [comment]
This is a diagnostics issue, it should complain that strings aren't parseable (use `bytes` instead).
