### ISSUE TITLE
plugin-jit.cc missing needed #includes

### ISSUE THREAD

**Issue by duffy-corelight** [zeek/spicy#340]
```
[ 58%] Building CXX object zeek/plugin/CMakeFiles/Zeek-Spicy.darwin-x86_64.dir/src/plugin-jit.cc.o
/usr/local/etc/spicy/zeek/plugin/src/plugin-jit.cc:59:27: error: use of undeclared identifier
      'internal_const_val'
    hilti_options.debug = internal_const_val("Spicy::debug")->AsBool();
                          ^
/usr/local/etc/spicy/zeek/plugin/src/plugin-jit.cc:60:37: error: use of undeclared identifier
      'internal_const_val'
    hilti_options.skip_validation = internal_const_val("Spicy::skip_validation")->AsBool();
                                    ^
/usr/local/etc/spicy/zeek/plugin/src/plugin-jit.cc:61:30: error: use of undeclared identifier
      'internal_const_val'
    hilti_options.optimize = internal_const_val("Spicy::optimize")->AsBool();
                             ^
/usr/local/etc/spicy/zeek/plugin/src/plugin-jit.cc:89:32: error: use of undeclared identifier
      'internal_const_val'
    driver_options.dump_code = internal_const_val("Spicy::dump_code")->AsBool();
                               ^
/usr/local/etc/spicy/zeek/plugin/src/plugin-jit.cc:90:35: error: use of undeclared identifier
      'internal_const_val'
    driver_options.report_times = internal_const_val("Spicy::report_times")->AsBool();
                                  ^
/usr/local/etc/spicy/zeek/plugin/src/plugin-jit.cc:92:32: error: use of undeclared identifier
      'internal_const_val'
    for ( auto s : util::split(internal_const_val("Spicy::codegen_debug")->AsStringVal()->ToStdSt...
                               ^
/usr/local/etc/spicy/zeek/plugin/src/plugin-jit.cc:99:48: error: use of undeclared identifier
      'internal_const_val'
    if ( auto r = hilti_options.parseDebugAddl(internal_const_val("Spicy::debug_addl")->AsStringV...
```
solved by adding at plugin-jit.cc(20):
```
#include <zeek-spicy/autogen/config.h>
#include <zeek-spicy/file-analyzer.h>
```

**Comment by rsmmr** [comment]
Which Zeek version is this, and are you building Spicy in debug or release mode? (I'm asking because I'm wondering why CI isn't catching this)

**Comment by duffy-corelight** [comment]
I am still on the zeek version that I have been all along, which was an incremental ./zeek/build/zeek-config --version
3.2.0-dev.137

The internal_const_val declaration is in ./zeek/src/Var.h 
extern Val* internal_val(const char* name);
extern Val* internal_const_val(const char* name); // internal error if not const

and the AsBool and its siblings in ./zeek/src/Val.h 

My conjecture is that amongst the #include chain of plugin-jit.cc is something which in release versions of zeek does itself #include Var.h and Val.h 

But since plugin-jit.cc itself now uses the internal_const_val and AsBool, etc. itself, it should do #include Var.h and Val.h itself, potentially redundantly, but essential in case whatever of zeek does those fortuitous #include Var.h and Val.h but might not always need to, could evolve that away.

**Comment by rsmmr** [comment]
Ah, I remember now, it's a git development version. Spicy currently supports Zeek 3.0 and 3.1. I'd rather not target 3.2-dev yet because things keep changing there (we're cleaning up/restructuring includes and other stuff). Spicy will update once 3.2 stabilizes. I'll close this and recommend you switch to 3.1 (you can just change to the `release/3.1` branch in git if you prefer)
