### ISSUE TITLE
print not parameterizing what follows -- treats the whole line as an expression

### ISSUE THREAD

**Issue by duffy-corelight** [zeek/spicy#349]
```
module Issue_349_print_passing_the_optional;

public type wantsSpcAfterMinus = unit {
    var theSymbol: string &optional;
  minusSign: /\-*/;
    on minusSign {
      self.theSymbol = "-";
    }
    on %done {
      print ("!%s ", (self.?theSymbol,));
    }
};
```
outputs:
```
printf "4" | /usr/local/etc/spicy/build/bin/spicy-driver /usr/local/etc/tmp/Issue_349_print_not_parameterizing.spicy
("!%s ", ("-"))
```

**Comment by duffy-corelight** [comment]
I don't know if the .? operator is key. I was totally surprised at this, and here report a reproducible for what I have seen. 
spicy-driver v0.4.0-317.dirty (master bfe85d9)

**Comment by rsmmr** [comment]
This looks as expected to me. Did you mean to use the '%` operator?

```
print "!%s " % self.?theSymbol;
```

This might still not quite work though, the `.?` operator will throw if the field isn't set. There's `?.` to test if the field is set.

**Comment by duffy-corelight** [comment]
If that output looks right to you, this ticket can close. The use of a comma where % is typical was inadvertent, but I had not realized that with first argument containing a % character, but which did not then apply the % operator, that wouldn't merit a syntax-error report of "not enough arguments". You have a valid point, that in the absence of % operator (even though passed to print), the first argument is untreated content of the string. My expectation, which caused me to report this, was what felt like a similar scenario: if the count of %-needing-arguments in the format string doesn't match the count of tuple-elements on the two sides of % operator, there is a syntax error reported. Here, the comma caused this to be multiple arguments passed to print, a capability which I had never (intentionally or unintentionally) used before.
