### ISSUE TITLE
Documentation issues (just add to it when you notice something)

### ISSUE THREAD

**Issue by rsmmr** [zeek/spicy#352]
New documentation ticket, just add comments for anything wrong or missing.

**Comment by non-descriptive** [comment]
Typo in repo `README.md`.
`[Zeek](https://www.zeek.org>)` have an extra `>`at the end of the link

**Comment by rsmmr** [comment]
`time` and `interval` types aren't documented.

**Comment by bbannier** [comment]
`optional` is not documented. In addition to the API it would be nice to add an example checking e.g., whether an `&optional` field is set in the section _Unit Variables_.

**Comment by duffy-corelight** [comment]
documentation should contain a list of reserved keywords

**Comment by rsmmr** [comment]
Update Zeek debugging to cover the HLTO usage model. Also double check that everything still works the same way as described.

**Comment by duffy-corelight** [comment]
iterator + should not have the same wording as +=
Also iterator + operator is commutative, so mention both versions: value on the left and on the right.

Existing text:
```
iterator<bytes> + uint<64> → iterator<bytes>
Advances the iterator by the given number of bytes.

iterator<bytes> += uint<64> → iterator<bytes>
Advances the iterator by the given number of bytes.
```
should be
```
uint<64> + iterator<bytes> → iterator<bytes>
iterator<bytes> + uint<64> → iterator<bytes>
Returns an iterator which is pointing the given number of bytes later than the one passed in.

iterator<bytes> += uint<64> → iterator<bytes>
Advances the iterator by the given number of bytes.
```

**Comment by duffy-corelight** [comment]
Is it worth mentioning what operator * returns for iterators greater than or equal to end()?
```
Iterator Operators

*iterator<bytes> → uint<8>
Returns the character the iterator is pointing to.
```
could say:

```
Iterator Operators

*iterator<bytes> → uint<8>
Returns the character the iterator is pointing to. Returns 0 if the iterator is pointing to greater than or equal to end.
```

**Comment by duffy-corelight** [comment]
The pair of find() documentation are using "last position" which is ambiguous wrt the end position, and what find does return is an iterator pointing past all content.

Existing text:
```
If needle was not found, the boolean will be false and the iterator will point to the last position so that everything before it is guaranteed to not contain...
```
could be
```
If needle was not found, the boolean will be false and the iterator will point past all content to the end position, so that everything seen is guaranteed to not contain...
```

**Comment by rsmmr** [comment]
Add a section on different ways to use Spicy parsers from custom host applications.
