### ISSUE TITLE
segfault when .evt event doesn't match .zeek event

### ISSUE THREAD

**Issue by dopheide-esnet** [zeek/spicy#365]
Re: conversation in Slack on #spicy channel.

Specifically in the attached examples... in .evt:
on SM::DATA -> event SM::data($conn, $is_orig, self.first_byte);

in .zeek
#event SM::data(c: connection, is_orig: bool, first_byte: int)
event SM::data(c: connection, first_byte: int)

[SM.tar.gz](https://github.com/zeek/spicy/files/4726294/SM.tar.gz)

**Comment by rsmmr** [comment]
This is supposed to be caught at runtime, I'll check what's going on.
