### ISSUE TITLE
&convert cannot deduce type when working on list

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#368]
While `&convert` can be used to transform scalar values with user-provided functions, it fails to deduce the correct destination type for lists as of fa3e0b22160fa059092782fe3586e2482942dc06.
```
$ cat /tmp/bla.spicy
module Foo;

function fn1(x: uint8): uint8 { return x; }

function fn2(xs: vector<uint8>): vector<uint8> { return xs; }

public type P = unit {
    x: uint8 &convert=fn1($$);
    xs: uint8[] &size=1 &convert=fn2($$); # Fails to deduce.
};
```

```
$ spicyc -j /tmp/bla.spicy
[error] /tmp/bla.spicy:9:9: type '<unknown type>' cannot be used for function parameter
[error] spicyc: aborting after errors
```

**Comment by rsmmr** [comment]
So I got a pretty simple fix for this one, but there's more that's more complex: changing the type of the vector through `&convert` doesn't work. Need to dig in more there.
