### ISSUE TITLE
Return value type coercion fails for tuples of tuples

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#385]
As of 16c19edf264616d83c0e973d849cc584a52a70d0 the following code does not typecheck:
```
$ cat /tmp/foo.spicy
module Test;

public function foo(): tuple<tuple<uint64>> { return ((0, )); }
```
```
$ spicyc /tmp/foo.spicy -j
[error] /tmp/foo.spicy:3:47: cannot coerce expression '((0))' of type 'tuple<uint<64>>' to type 'tuple<tuple<uint<64>>>'
[error] spicyc: aborting after errors
```

Note that the return value already has the correct type and no type coercions are required. After we fix this we should check that this also works if we actually require a coercion, e.g., by narrowing the width of a such wrapped integer.

**Comment by rsmmr** [comment]
it's a typo, should be `return ((0, ), );`.

The syntax isn't pretty of course, we should allow `tuple(...)` for constructing tuples.
