### ISSUE TITLE
Missing return value not caught in validation

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#391]
As of 16c19edf264616d83c0e973d849cc584a52a70d0 we do not catch missing return values in non-void functions. Instead we inherit whatever semantics C++ has here. We should either reject such code at validation time, or alternatively introduce clean semantics about default return values to the Spicy language (I'd prefer rejecting such code as it is hard to understand and likely an error anyway).

```
module Test;
function foo(): uint32 {}
```

```.sh
$ spicyc /tmp/foo.spicy -j
Test.cc:18:73: warning: non-void function does not return a value
static auto __hlt::Test::foo() -> hilti::rt::integer::safe<uint32_t> {  }
                                                                        ^
1 warning generated.
```

**Comment by rsmmr** [comment]
This the same as #208 ?

**Comment by bbannier** [comment]
> This the same as #208 ?

Yes, I think so. Not returning a value from a non-void function triggers UB, so whatever additional behavior we see in #208 is not interesting.

**Comment by bbannier** [comment]
Duplicates #208
