### ISSUE TITLE
Cannot access elements of vector<bool>

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#392]
As of 16c19edf264616d83c0e973d849cc584a52a70d0 we invoke calls to `std::vector<bool>::data` which does not exist since `std::vector<bool>` is a proxy class.

```$ cat /tmp/foo.spicy
module Foo;

local xs: vector<bool>;
xs[0];
```

```
$ spicyc /tmp/foo.spicy -j
In file included from Foo.cc:6:
In file included from /usr/local/Cellar/spicy/HEAD-ff5b3c2/include/hilti/rt/libhilti.h:15:
In file included from /usr/local/Cellar/spicy/HEAD-ff5b3c2/include/hilti/rt/types/all.h:5:
In file included from /usr/local/Cellar/spicy/HEAD-ff5b3c2/include/hilti/rt/types/address.h:9:
In file included from /usr/local/Cellar/spicy/HEAD-ff5b3c2/include/hilti/rt/types/bytes.h:12:
In file included from /usr/local/Cellar/spicy/HEAD-ff5b3c2/include/hilti/rt/types/regexp.h:9:
In file included from /usr/local/Cellar/spicy/HEAD-ff5b3c2/include/hilti/rt/types/stream.h:21:
/usr/local/Cellar/spicy/HEAD-ff5b3c2/include/hilti/rt/types/vector.h:328:19: error: no member named 'data' in 'std::__1::vector<bool, std::__1::allocator<bool> >'
        return V::data()[i];
                  ^
Foo.cc:20:7: note: in instantiation of member function 'hilti::rt::Vector<bool, std::__1::allocator<bool> >::operator[]' requested here
    xs[hilti::rt::integer::safe<std::uint64_t>{0u}];
      ^
1 error generated.
```

The calls to `std::vector::data` originate in `operator[]` implementations. We need to check how we can support these for vectors of bool, in particular for assignment for vector elements.

**Comment by bbannier** [comment]
The workaround here is to either (a) reimplement `rt::Vector` for `bool` so it does not use `vector<bool>`, but e.g., `vector<uint8_t>` as base class, or (b) to introduce a wrapper type for bools to disable the `vector<bool>` specialization. The former seems like a lot of work for very little benefit while the later cannot happen in `hilti-rt`, but probably in the codegen.

@rsmmr, WDYT about introducing a `rt::Boolean` type (probably something like a strong typedef should be enough) which can then be used by either of `type::Bool` and/or `ctor::Bool`?

**Comment by rsmmr** [comment]
Yeah, that sounds ok. It's a bit unfortunate that we need to do that just because of the vector use case, but I can't think of another way either that would seem preferable.
