### ISSUE TITLE
`Spicyc` doesn't support `.spicy` file when built with static libs

### ISSUE THREAD

**Issue by Jason--n** [zeek/spicy#400]
Compiler : LLVM 10 on MacOS、GCC 10 on  CentOS 8
Build Type: Debug

I tried two platform mentioned above，and it ended up with the same result. When built with static libs, the `Spicyc` binary can't compile file with extention `.spicy` and shows an error "unsupported file type".

I used gdb to debug this binary, and found out that the static variable  in `spicy/src/compiler/plugin.cc` which should be initialized with function `spicy_plugin` did not be initialized. There was no symbol `spicy_plugin` in the binary.

When built with dynamic libs, `Spicyc` **can** compile `.spicy` file.

**Comment by rsmmr** [comment]
Building with static libraries hasn't seen a lot of testing. I bet this is because of the global constructor not running, we may need to that initialization differently so that it works with static libs as well.

**Comment by Jason--n** [comment]
Yes, the global constructor can't be called because there is even no symbol in the binary `spicyc`. When built with static libraries, the binary is linked with some symbol it needs and the static plugin initializer variable in the `.cpp` file is considered unnecessary. As a result, there will be no static initializer symbol in the `spicyc` binary. If we want to make the static initializer included in the binary, we need to tell the compiler.

GCC and Clang both provide a compiler option to include all the symbols in the static library in the target.

For GCC:
> --whole-archive
>For each archive mentioned on the command line after the --whole-archive option, include every object file in the archive in the link, rather than searching the archive for the required object files. This is normally used to turn an archive file into a shared library, forcing every object to be included in the resulting shared library. This option may be used more than once.

For Clang:
> -all_load   Loads all members of static archive libraries.

I test clang option `-all_load` on MacOS and it works. But the binary size is a little bigger than the previous one.

**Comment by Jason--n** [comment]
I have made a pull request #414. Maybe it's not a good idea to include all the symbols of the static library in the executables. But it solves the problem indeed.
