### ISSUE TITLE
time and interval datatypes in the 5.2.5. Types documentation

### ISSUE THREAD

**Issue by duffy-corelight** [zeek/spicy#405]
time and interval datatypes are needed in the 5.2.5. Types documentation

**Comment by duffy-corelight** [comment]
Perhaps postponing their increased visibility until they are ready. While experimenting, I encountered that an expression cannot be passed to the time() constructor, and then another scenario that reported as C++ syntax error:
```
module Issue_392;
import spicy;
global momentaryNow = spicy::current_time();

public type soonAfterThatToday = unit {
#    var futureWhen: time = time(momentaryNow + 0.0000001);
    var futureWhen: time = time(0.0000001);
    on %init {
      self.futureWhen = self.futureWhen + momentaryNow;
      assert (momentaryNow < self.futureWhen);
#      print ("%s" % (spicy::strftime("%D", time(1609372800)),));
      print ("%s, %s" % (momentaryNow, self.futureWhen));
    }
};
```
which while trying to assign the sum in the declaration, as commented-out line 6 shows, produced:
```
[error] /usr/local/etc/tmp/Issue_392_microsecond_precision.spicy:6: syntax error, unexpected identifier, expecting real value or unsigned integer value or '+' or '-'
[error] spicy-driver: spicy-driver: parse error
```
then trying doing addition (which shouldn't work), as a QA because subtraction had been broken until #396 fixed that, it produced:
```
Issue_392.cc:80:26: error: no viable overloaded '='
    (*__self).futureWhen = (*__self).futureWhen + Issue_392::__globals()->momentaryNow;
    ~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/duffy/Documents/work/Corelight/projects/spicy/hilti/include/hilti/rt/types/time.h:47:11: note: candidate function not viable: no known conversion from 'int' to 'const hilti::rt::Time' for 1st argument
    Time& operator=(const Time&) = default;
          ^
/Users/duffy/Documents/work/Corelight/projects/spicy/hilti/include/hilti/rt/types/time.h:48:11: note: candidate function not viable: no known conversion from 'int' to 'hilti::rt::Time' for 1st argument
    Time& operator=(Time&&) noexcept = default;
          ^
1 error generated.
```

**Comment by rsmmr** [comment]
I'll close this as the lack of documentation is recorded in #352 already.

The `time()` constructor's lack of taking an expression is on purpose: it's meant as creating a literal time constant, similar to how `"..."` creates a literal string constant. I couldn't come up with a better syntax, athough I see how it can be confusing. Maybe we should just make it take an expression (but we have more cases of this, e.g., the integer ctors `int16(1234)`.) 

Please file a separate ticket for addition problem.
