### ISSUE TITLE
Documentation meta issue (just add to it when you notice something in the docs)

### ISSUE THREAD

**Issue by rsmmr** [zeek/spicy#441]

**Comment by rsmmr** [comment]
Add end-to-end file analyzer example.

**Comment by rsmmr** [comment]
Document properties that can be set at unit or module level (e.g., `%byte-order`)

**Comment by rsmmr** [comment]
Explain how to use Spicy enums from Zeek. note that they need to be `public`.

**Comment by duffy-corelight** [comment]
`write` isn't in the 5.2.8.1 list https://docs.zeek.org/projects/spicy/en/latest/programming/language/appendix.html#reserved-keywords

**Comment by duffy-corelight** [comment]
`filter` `forward` and `sink` also aren't in the 5.2.8.1 list

**Comment by duffy-corelight** [comment]
`self` isn't in the 5.2.8.1 list

**Comment by duffy-corelight** [comment]
`connect` isn't in the 5.2.8.1 list

**Comment by duffy-corelight** [comment]
`bitfield` isn't in the 5.2.8.1 list

**Comment by duffy-corelight** [comment]
In 5.1.6.8 Vector
standard field specification definining how to parse the vector elements.
should be
standard field specification defining how to parse the vector elements.

**Comment by rsmmr** [comment]
Ah, it's generating the reserved list from the wrong source, will fix (some of that are not reserved words though, write/forward/etc are method names)

**Comment by duffy-ocraven** [comment]
On https://docs.zeek.org/projects/spicy/en/latest/programming/language/types.html
in 5.2.5.2
Each RANGE has one of the forms LABEL: A or LABEL: A..B where A and B are a bit numbers.
should be
Each RANGE has one of the forms LABEL: A or LABEL: A..B where A and B are bit numbers.

and
in 5.2.5.5
Enum types associate labels with a numerical values.
should be
Enum types associate labels with numerical values.

**Comment by duffy-ocraven** [comment]
On https://docs.zeek.org/projects/spicy/en/latest/programming/parsing.html#unit-parameters
```
Fields may use an attribute &requires=EXPR to enforce additional constraints on their values. EXPR must a be boolean expression that will be evaluated after the parsing for the field has finished,
```
should be
```
Fields may use an attribute &requires=EXPR to enforce additional constraints on their values. EXPR must be a boolean expression that will be evaluated after the parsing for the field has finished,
```

**Comment by rsmmr** [comment]
The `begin()`/`end()` operators aren't documented (more generic operators may be missing too?)

**Comment by duffy-ocraven** [comment]
https://docs.zeek.org/projects/spicy/en/latest/programming/parsing.html#unit-hooks
```
Field and container hooks may be directly attached to their field, skipping the on ... part:

type Foo = unit {
    x: uint32 { ... }
    v: unint8[] foreach { ... }
}
```
has typo unint8

**Comment by duffy-ocraven** [comment]
In section 5.2.5.21
unit .? `<field>` → `<field type>`
... a context that specfically allows for that situation (such as, inside the Zeek plugin’s evt files).
should be 
... a context that specifically allows for...

**Comment by duffy-ocraven** [comment]
In section 5.2.6.12
```
If an else block is specified, that will executes once the COND evaluates to false at the loop beginning. It will not execute if the loop aborts with a break.
```
should be
```
If an else block is specified, that will execute just once, and only if the COND evaluates to false at the loop beginning. It will not execute if the loop aborts with a break.
```

**Comment by duffy-ocraven** [comment]
In section 5.2.6.12
```
A while-loop that executed BLOCK for as long as the boolean COND evaluates to true. 
```
should be
```
while introduces a loop, that executes BLOCK, for as many times as the boolean COND each time evaluates to true. 
```

**Comment by duffy-ocraven** [comment]
5.1.1. Basics section is eleven screenfuls long, without any numbered subsections. It could benefit from subsections in the Table-of-Contents.

**Comment by duffy-ocraven** [comment]
In 5.2.5.17. Stream
If needle was not found, the boolean will be false and the iterator will point to the last position so that everything before that is guaranteed to not contain even a partial match of needle (in other words: one can `trim` until that position and then restart the search from there if more data gets appended to the underlying stream value). 

the fonting of trim is odd, although the word trim would be fine. I don't think there is an operator named `trim`.

**Comment by duffy-ocraven** [comment]
Section 5.2.5.4. Bytes
```
find(needle: bytes) → tuple<bool, iterator<bytes>>
Searches needle in the value’s content. Returns a tuple of a boolean and an iterator. If needle was found, the boolean will be true and the iterator will point to its first occurrence. If needle was not found, the boolean will be false and the iterator will point to the last position so that everything before it is guaranteed to not contain even a partial match of needle. Note that for a simple yes/no result, you should use the in operator instead of this method, as it’s more efficient.
```
should rephrase as:
```
... will point to the latest possible position such that everything before that can be discarded, as it is guaranteed to not contain even an initial partial match of needle. The portion starting at the returned value might match the whole needle if additional bytes are appended.
```
Or for bytes, does returning an iterator that is equal-to end() always makes sense.

**Comment by duffy-ocraven** [comment]
In 5.2.5.14. Regular Expression
the list of five items:
`Supported character classes are: [:lower:], [:upper:], [:digit:], [:upper:], [:blank:].`
has `:upper:` twice.

**Comment by bbannier** [comment]
I made a pass over the comments in this issue and created PR #641 with fixes for outstanding issues. I also created separate issues for items that still need work.

I marked comments with :+1: if they are already fixed or are part of an in-flight PR, and :-1: if no work is needed.

I am closing this issue now as we properly track remaining work on a more granular level elsewhere now.
