### ISSUE TITLE
provide the  not in  operator

### ISSUE THREAD

**Issue by duffy-ocraven** [zeek/spicy#450]
`!(a in set)` is the current supported syntax. But: `a not in set` both reads more intuitively and avoids the not being applied across more than was intended.

spicy operator precedence does a pretty good job so far of not applying that leading ! to an expression, as long as there is no operator which can be on the right of the parentheses and bind tighter than ! does. But ! is only third level and spicy attributes such as &size bind quite tightly.

Over in #zq on brim Slack, on 14-Jul Phil Rzewski expressed: There's not a not in operator. You were on the right path with !(a in set) (or you could have done not (a in set)). We can think about making a change there as well. In prior discussions we've often shied away from making multiple ways to achieve the same thing the language, and not is already there to invert other logic. However, it doesn't seem to be helping here since it exposed the other usability problems with the left to right eval, such that you'd have to be double-wrapping to (not (a in set)) in order to put it as the first search term, which is, indeed, pretty ugly compared to a not in set.

**Comment by rsmmr** [comment]
Not quite what the relationship to `zq` is here?

**Comment by duffy-corelight** [comment]
The #zq discussion was merely where I was reading, and had the Aha! moment, that even in spicy: !(a in set) will not work intuitively, if
!(a in set).mmbr or something with similarly high precedence, were expressed on the right-hand side of the parentheses. Very subtle!

**Comment by rsmmr** [comment]
I suggest we follow Zeek's `!in` here.
