### ISSUE TITLE
Inherit Byte Order Setting

### ISSUE THREAD

**Issue by grigorescu** [zeek/spicy#452]
Right now, I have code that looks like this:

```
type Foo = unit {
    bar: Bar;
}

type Bar = unit {
    f1: uint32 &byte-order = spicy::ByteOrder::Little;
    f2: uint32 &byte-order = spicy::ByteOrder::Little;
    f3: uint32 &byte-order = spicy::ByteOrder::Little;
    f4: uint32 &byte-order = spicy::ByteOrder::Little;
}
```
Especially for a file analyzer, it'd be nice to be able to set the default ByteOrder in one place, at the top level. Additionally, it'd be nice if I could do `bar: Bar &byte-order = spicy::ByteOrder::Little;` and have all the elements in Bar inherit that, unless specifically overriden.

**Comment by rsmmr** [comment]
That's possible already, but looks like that's not documented yet, I'll add that.

You can set byte-order either globally for the module:

```
module Test;

%byte-order = spicy::ByteOrder::Little;

type Foo = unit {
...
```

or for a specific unit:

```
type Foo = unit {
  %byte-order = spicy::ByteOrder::Little;
   ...
```
