### ISSUE TITLE
Impose a (tunable) limit on how large field could grow, to disallow remotely-controlled memory exhaustion

### ISSUE THREAD

**Issue by duffy-corelight** [zeek/spicy#458]
Impose a limit on how large a flowbuffer field could grow, in order to disallow remotely-controlled packet data to cause growth unbounded, leading to memory exhaustion. Bro 2.6.2 added that as a generalized limit for how large flowbuffers are allowed to grow, tunable by setting "BinPAC::flowbuffer_capacity_max". per Release Notes  https://raw.githubusercontent.com/zeek/zeek/3b5a9f88ece1d274edee897837e280ef751bde94/NEWS

**Comment by rsmmr** [comment]
Spicy doesn't have a flow buffer, so this doesn't apply directly. But the underlying challenge remains: (1) there are some places where data is buffered, and imposing a limit on those would be good; and (2) values stored into unit fields can easily get large if the user isn't careful, and a mechanism to help with that would be useful.

**Comment by rsmmr** [comment]
Tracked by #460.
