### ISSUE TITLE
Linker glue can introduce incorrect enum redeclarations

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#500]
Given a module
```
module Foo;

type E = enum {
    A = 0x01
};

type P = unit {
    x: uint16 &convert=E($$);
};
```

the code generated from `spicyc -cK` will include a declaration for `E`
```.cpp
namespace __hlt::Foo {
    struct P;
    enum class E : int64_t { A = 1, Undef = -1 };
}
```
which the linker glue will attempt to forward-declare the enum as
```.cpp
using E = enum class E : int64_t { A = 1, Undef = -1 };
```

Attempting to compile that code will fail since `E` is redeclared.

Note that this redeclaration is only emitted if `E` is used like in above unit.

**Comment by rsmmr** [comment]
I believe what's happening here is that the linker code is just output as if it were standalone. I.e.,  `-K` is  just appending what would normally be produced by `-l` to the output of `-c`. The problem with that  is that we have just a single translation unit now in which things end up getting declared twice. We will either adapt the output of `-K` to take into account what's been emitted already, or remove the option altogether (it's just for convince when compiling just a single input file).

**Comment by bbannier** [comment]
FTR, in this particular scenario I am using `-K` to emit hook declarations which I do not care about, but which are needed to link.
