### ISSUE TITLE
Bitwise dissection of protocols

### ISSUE THREAD

**Issue by konradcc** [zeek/spicy#501]
Hi, 

I want to dissect a protocol bit by bit.

The protocol structure looks like this: 2 Bits, 4 Bits, 2 Bits, 3 Bits and so on.
Now I want to dissect bit by bit.

In the documentation I found the bitfield type.
Could this be a solution for me to read out bit by bit?
Is this possible and how would you do it preferably with spicy?

Thanks in advance!

**Comment by sethhall** [comment]
Look here for an example of how to do it: https://github.com/zeek/spicy/blob/master/tests/spicy/types/bitfield/parse.spicy

You can parse individual bits into a field and/or sequences of bits.
