### ISSUE TITLE
comparison operations don't work because 53bits of precision in a double

### ISSUE THREAD

**Issue by duffy-corelight** [zeek/spicy#504]
There are only 53bits of precision in a double. Nanosecond precision had almost immediately already started to degrade back in early April 1970. Even microsecond precision will no longer be available after sometime in 2224. Comparison operations that are reasonable to expect, such as 1584567890.0000007 < 1584567890.0000008 already don't work today.

(please excuse that I had already coded this demo script for zeek as a comment to https://github.com/zeek/zeek/pull/1171, but spicy if it is using double for interval would be similar).
```
event zeek_init()
    {
    local earlyIndistinguishableTime = 1584567890.0000007 secs;
    local laterIndistinguishableTime = 1584567890.0000008 secs;
    print earlyIndistinguishableTime < laterIndistinguishableTime;
    print fmt("%23.9f", earlyIndistinguishableTime);
    print fmt("%23.9f", laterIndistinguishableTime);
    }
zeek -b ~/Documents/work/zeek/interval_experiments.zeek
F
   1584567890.000000715
   1584567890.000000715
```
If spicy is claiming nanoseconds, or any precision-specifier past 6 at this point in the epoch where 31 bits have already been consumed by the seconds, it is timely to improve the underlying datatype (probably in parallel with Zeek's) for representing time and interval.

**Comment by bbannier** [comment]
Can you point us to some Spicy code which shows this problem? `Interval` internally stores `int64_t` values and if it is constructed from a nanosecond value with `interval_ns` (instead of from a second value with `interval`), there should not be any loss of precision,
```
module foo;

global a = interval_ns(15845678900000007);
global b = interval_ns(15845678900000008);
assert a != b;
assert a < b;
assert !(b < a);

global c = b - a;
print(c.nanoseconds()); # Prints '1'.
```

**Comment by duffy-corelight** [comment]
Sorry, I had missed that giant step forward in Spicy's excellent evolution!
Upon examining https://github.com/zeek/spicy/blob/master/hilti/include/rt/types/interval.h, I believe you have implemented a working solution, and the one which I've commented for Zeek to adopt if the enhancement to timestamp_precision in https://github.com/zeek/zeek/pull/1171 goes forward.
