### ISSUE TITLE
integer literal too large to be represented as signed integer

### ISSUE THREAD

**Issue by duffy-ocraven** [zeek/spicy#513]
Inadvertently when I hadn't yet changed interval( to interval_ns( in these statements, I triggered this pair of compiler warnings showing completely different decimal literals. Note that in the .spicy they differ by 100. In the warning they are the same number.

Do we want to make that fatal, instead of warning or do we want to let that interpretation happen? The run-time did eventually hilti::rt::Overflow: integer overflow in this case.

A pernicious gray-area could arise where an expression involving multiple integer literals some of which are too large, ultimately due to a difference operation brings it back within the range representable by the signed type. Then at run-time there wouldn't be a hilti::rt::Overflow. 

But foremost to worry about, in the .spicy they differ by 100. In the warning they are the same number.
```
module Issue_513_no_unit;

global a = interval(1584567890000000700);
global b = interval(1584567890000000800);
assert a != b;
assert a < b;
assert !(b < a);

global c = b - a;
print(c.seconds()); # still succcessfully preserves and prints a significant '1'.
```
produces
```
printf "3\n" | build/bin/spicy-driver  /usr/local/etc/tmp/Issue_513_integer-overflow.spicy 
Issue_513_no_unit.cc:28:77: warning: integer literal is too large to be represented in a signed integer type, interpreting as unsigned
    __globals()->a = hilti::rt::Interval(hilti::rt::integer::safe<int64_t>(-9223372036854775808), hilti::rt::Interval::NanosecondTag());
                                                                            ^
Issue_513_no_unit.cc:29:77: warning: integer literal is too large to be represented in a signed integer type, interpreting as unsigned
    __globals()->b = hilti::rt::Interval(hilti::rt::integer::safe<int64_t>(-9223372036854775808), hilti::rt::Interval::NanosecondTag());
                                                                            ^
2 warnings generated.
uncaught exception hilti::rt::Overflow: integer overflow
```

**Comment by rsmmr** [comment]
Yeah, we should make that fatal on the Spicy-side.
