### ISSUE TITLE
full nanosecond precision in time won't display

### ISSUE THREAD

**Issue by duffy-ocraven** [zeek/spicy#515]
Can't get the full nanosecond precision in time to display.
```
module Issue_515_700_nanoseconds;

global a = time_ns(1600400000000000700);
print a;
print "%23.33s" % (a,);
```
produces
```
build/bin/spicy-driver  /usr/local/etc/tmp/Issue_515_round_at_7th.spicy 
2020-09-18T03:33:20.000001024Z
2020-09-18T03:33:20.000001024Z
[error] spicy-driver: no parsers available
```

**Comment by rsmmr** [comment]
There's a `nanoseconds` method on `time`. Printing the result would be the better way to get that resolution I'd say. However, there's a bug there too: it `nanoseconds` returns a `real`, but should return a `uint64` (same for `interval`).
