### ISSUE TITLE
Improve JIT speed

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#52]
While the Spicy/HILTI code generation isn't exactly fast itself yet, most time is currently actually spent in the JIT phase compiling and linking the C++ code. We should improve that as much as we can. There might be redundant work being done during linking, and we might also be able to rework some of the `include/rt` code to compile more quickly.

Note: `hiltic`/`spicyc` have options `-R` to show a break down of where they spend their time.

**Comment by rsmmr** [comment]
Closing this as we have done some work to improve this already and can just tweak further over time.
