### ISSUE TITLE
#if ZEEK_VERSION_NUMBER >= 30200 makes executable specific to "zeek version at compile time"

### ISSUE THREAD

**Issue by duffy-corelight** [zeek/spicy#520]
conditional `#if ZEEK_VERSION_NUMBER >= 30200` in `spicy/zeek/plugin/include/zeek-spicy/zeek-compat.h` and in `zeek/plugin/include/protocol-analyzer.h` (spicy-0.4.0-884), makes the resulting compiled executables specific to the zeek version which was configured "at compile time", on the build-engineer's machine.

**Comment by duffy-corelight** [comment]
Not just an issue for intermediates like 3.2.0-dev.137 The resulting compiled zeek-spicy plugin executable is specific to the zeek version which was configured "at compile time", and (if I understand correctly) won't operate correctly if deployed on a configuration where the zeek version is on the other side of the divide (i.e. 3.1.0 vs 3.2.0)

**Comment by duffy-corelight** [comment]
Not work, I mean only in the sense of https://github.com/zeek/spicy/issues/519 I have not seen any other ways in which it might or does not work. And I haven’t tested #519 on a true 3.1.0 build.

**Comment by rsmmr** [comment]
That's right, but we can't avoid it unfortunately. Compiled Zeek analyzers will always be specific to version they were built for because Zeek doesn't provide binary compatibility between releases, so no point of being particularly careful on our end either.
