### ISSUE TITLE
Add reflection API for generated Spicy parsers

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#56]
This is so a Spicy host applications can discover what's being parsed without specific knowledge about each parser.

We can probably reuse some existing, light-weight C++ reflection library to instrument the generated parsing structs. It will need to go into the HILTI codegen code then.

**Comment by rsmmr** [comment]
Being worked on [in this branch](https://github.com/zeek/spicy/tree/topic/robin/gh-38-spicy-dump).

**Comment by rsmmr** [comment]
Done with #347 .
