### ISSUE TITLE
cannot coerce expression '0x1.34d9dd1ap+30' of type 'real' to type 'time'

### ISSUE THREAD

**Issue by duffy-ocraven** [zeek/spicy#565]
```
module Issue_565;

global t1: time = 1295415110.5;
```
outputs
```
./spicy/build/bin/spicy-driver -S /usr/local/etc/tmp/Issue_565_time_assigned_real.spicy 
[error] /usr/local/etc/tmp/Issue_565_time_assigned_real.spicy:1:18-3:32: cannot coerce expression '0x1.34d9dd1ap+30' of type 'real' to type 'time'
[error] spicy-driver: aborting after errors
```
This a correctly reporting a syntax error there, fixed by this code instead
```
global t1: time = time(1295415110.5);
```
but the text with dd1ap+30 in the error text doesn't look like it is intentional.

**Comment by duffy-ocraven** [comment]
Perhaps this is a mix of hexadecimal mantissa and decimal exponent?

**Comment by duffy-ocraven** [comment]
I just learned at https://www.gnu.org/software/libc/manual/html_node/Floating_002dPoint-Conversions.html that %a outputs a mix of hexadecimal mantissa and decimal power-of-2 exponent, and that diagnostic use-cases are its intent. This format might thus be warranted here, and if this is intentional, then this ticket can be closed.

**Comment by rsmmr** [comment]
Yeah, it's intentional. Can't say I'm a big fan of this style (because it's so unusual) but it's what we are currently using at a few places.
