### ISSUE TITLE
Align CI platforms with Zeek

### ISSUE THREAD

**Issue by rsmmr** [zeek/spicy#582]
Zeek's policy is documented [here](https://github.com/zeek/zeek/wiki/Platform-Support-Policy), we should do the same for our CI.

**Comment by rsmmr** [comment]
The two (now closed) tickets referenced above already have starting points for adding Debian 10 and FreeBSD.

**Comment by bbannier** [comment]
We require additional builds for the following platforms:

- debian-9
- debian-10
- fedora-32
- fedora-33
- freebsd-12.2
- freebsd-11.4
- ubuntu-20.04
- ubuntu-16.04

**Comment by bbannier** [comment]
With #627 merged we still need to add the following platforms:

- macos Big Sur
- freebsd-12.2
- freebsd-11.4

**Comment by bbannier** [comment]
Closing this as CI now covers macOS Big Sure, freebsd-11 and freebsd-12.
