### ISSUE TITLE
Zeek plugin does not compile with a Zeek with '--enable-debug'

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#597]
As of 2cbe6323c8fee0d69aa7eb670c71ab2371cf4de7 Spicy cannot be build against a Zeek with `--enable-debug` (tested against zeek/zeek@218c24f55b02eb2f9debf1295ea38d8c2226d56e).

```
../zeek/plugin/src/plugin-jit.cc:35:5: error: no member named 'detail' in namespace 'spicy::zeek'; did you mean '::zeek::detail'?
    PLUGIN_DBG_LOG(*plugin::Zeek_Spicy::OurPlugin, "%s", std::string(msg).c_str());
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/bbannier/src/zeek/P/include/zeek/DebugLogger.h:23:41: note: expanded from macro 'PLUGIN_DBG_LOG'
#define PLUGIN_DBG_LOG(plugin, args...) zeek::detail::debug_logger.Log(plugin, args)
                                        ^~~~~~
/Users/bbannier/src/zeek/P/include/zeek/plugin/Plugin.h:22:46: note: '::zeek::detail' declared here
ZEEK_FORWARD_DECLARE_NAMESPACED(Frame, zeek::detail);
                                             ^
1 error generated.
```

The issue here seems to be that our call lives in the namespace `spicy::zeek` and Zeek defines `PLUGIN_DBG_LOG` as 

```.cpp
#define PLUGIN_DBG_LOG(plugin, args...) zeek::detail::debug_logger.Log(plugin, args)
```

Here, `zeek::detail::debug_logger` is looked up in lower scopes first and finds our `spicy::zeek` (which does not have `detail::debug_logger`), instead of referencing the correct `::zeek::detail`.

A fix could be to either provide a `::spicy::zeek::detail::debug_logger` (which could just forward to `::zeek::detail::debug_logger`), or for Zeek to always look for `::zeek::detail::debug_logger` in the definition of `PLUGIN_DBG_LOG` (this would assume that `zeek::detail::debug_logger` is not a customization point).

This issue was first [reported on Slack](https://zeekorg.slack.com/archives/C012CQV1K29/p1605886778101200).

**Comment by rsmmr** [comment]
(Also. zeek master isn't "officially" supported for Spicy as we don't have it in CI).
