### ISSUE TITLE
syntax for a &try field which is an optional field

### ISSUE THREAD

**Issue by duffy-ocraven** [zeek/spicy#608]
#606 adding &try backtracking (which is great), in some cases leaves a unit partially-constructed in the approach so far. For instance, the
tests/spicy/types/unit/backtrack-on-error.spicy
result is 
`[$a=b"1234", $foo=[$a=1, $b=(not set), $c=(not set)], $bar=[$a=1, $b=2, $c=3], $b=b"567890"]`
with no setting for foo.b and foo.c

The so-far existing operators for determining the is_set conditionality should be augmented in consideration of how to later inquire about the presence of foo in this situation. foo is optional and perhaps should be marked `&try &optional`, but more importantly, the section 5.2.5.11 Operator *optional, and section 5.2.5.21 Operators
unit ?. `<field>` → bool
unit . `<field>` → `<field type>`
unit .? `<field>` → `<field type>`
and
unset unit.`<field>` → void 
should do the intuitive thing.

**Comment by rsmmr** [comment]
`foo` will be set, but only partially initialized. You should be able to test for `foo.b`/`foo.c` being set using `?.` . Can you give an example of where that either doesn't work, or what you'd like to do that currently isn't supported?

**Comment by duffy-ocraven** [comment]
When I rebuild with a more recent spicy that has the &try support, I'll put all the Operators
```
unit ?. <field> → bool
unit . <field> → <field type>
unit .? <field> → <field type>
and
unset unit.<field> → void
```
through thorough scrutiny. I'll report any that seem unintuitive.

**Comment by duffy-ocraven** [comment]
What is your preferred mechanism for a high-level back-and-forth regarding, as Benjamin put it in commenting on the #606:  "we probably still need a better idea how we want error handling to finally look"? I opened this 608 ticket, for the aspect when &try is used for a field which is an optional field, which the existing backtrack-on-error.spicy code exactly manifests with paradigm: if what you see during parsing at the needful moment isn't the signature of the optional field, then treat the input-stream as omitting that optional field, and go on. That is one major paradigm we will want to support well in how error handling finally looks. I think that will be very common. But not all backtracking will be for support of treating the input-stream as omitting an optional field. I suggest &try &optional as the syntax to denote those times when it is.

**Comment by rsmmr** [comment]
GitHub has just enabled Discussions publicly, and I turned that on. That seems like the best place for back-and-forth on how to best do something. I'll open a thread there, just add any thoughts to it.

I'll leave this ticket open until you've tried out the operators.

**Comment by rsmmr** [comment]
Have you had a chance to try these further?

**Comment by duffy-ocraven** [comment]
Nope, I  haven't had a rebuild that includes the #606 added &try support yet.

**Comment by rsmmr** [comment]
I close this in favor of the Discussions thread.
