### ISSUE TITLE
Investigate type error on debian-10

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#629]
We still see the following failure on `docker_debian10`:

```
[#5] spicy.tools.spicy-driver-batch [installation] ... failed
  % 'btest-diff output' failed unexpectedly (exit code 1)
  % cat .diag
  == File ===============================
  [$data=b"12"]
  [$data=b"34"]
  [$data=b"56"]
  [$data=b"abcdef"]
  error for ID id1: mismatch in result type (/tmp/cirrus-ci-build/tests/.tmp/spicy.tools.spicy-driver-batch/spicy-driver-batch.spicy:15:16)
  error for ID id2: mismatch in result type (/tmp/cirrus-ci-build/tests/.tmp/spicy.tools.spicy-driver-batch/spicy-driver-batch.spicy:15:16)
  == Diff ===============================
  --- /tmp/test-diff.18419.output.baseline.tmp	2020-12-15 16:59:40.906470503 +0000
  +++ /tmp/test-diff.18419.output.tmp	2020-12-15 16:59:40.205405175 +0000
  @@ -2,3 +2,5 @@
   [$data=b"34"]
   [$data=b"56"]
   [$data=b"abcdef"]
  +error for ID id1: mismatch in result type (<...>/spicy-driver-batch.spicy:15:16)
  +error for ID id2: mismatch in result type (<...>/spicy-driver-batch.spicy:15:16)
  =======================================
  % cat .stderr
  [libspicy] initializing runtime
  [libspicy] registered parsers (w/ aliases):
  [libspicy]   80/tcp -> Test::X
  [libspicy]   80/tcp%orig -> Test::X
  [libspicy]   80/tcp%resp -> Test::X
  [libspicy]   Test::X -> Test::X
  [libspicy]   application/foo -> Test::X
  [libspicy] registered parsers for MIME types:
  [libspicy]   application/foo -> Test::X
  [libspicy] shutting down runtime
  [libspicy] destroying global state
  # user_time=0.001050 sys_time=0.000046 memory=54525952
```

What is curious is that when I patched `Resumable::get` to emit both the types of `Result` and `*_result` they both were a `View`, so I am unsure how this can result in a `bad_cast`. I bisected this down to 6cdef6967c824ecc342daf714f50bbbb9931685e which did some refactorings around `View`, `Resumable` and also `ParsingState`. By selectively rolling back the changes to `View` and `Resumable` the most likely candidate at this point is the change to `ParsingState` triggering this.

_Originally posted by @bbannier in https://github.com/zeek/spicy/issues/627#issuecomment-745561513_

**Comment by bbannier** [comment]
I patched the code emitting the `mismatch in result type` diagnostic to emit the numeric type ID. With that both the expected type `typeid(Result).hash_code()` and the actual type `_result->type().hash_code()` are identical.

**Comment by bbannier** [comment]
Probably worth looking into the actual addresses of the type infos instead of their hashes as some implementations compare the addresses instead of the hashes.

**Comment by bbannier** [comment]
The addresses of the type infos are identical as well.

**Comment by rsmmr** [comment]
Darn, now it's getting weird!

**Comment by bbannier** [comment]
This is https://stackoverflow.com/questions/45290296/stdany-across-shared-library-bounding-in-mingw.

**Comment by bbannier** [comment]
Inspired by https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90415 I checked whether replacing `std::any` with `std::experimental::any` in `hilti/runtime/include/fiber.h` was a sufficient fix on debian-10. Even with the fix the problem still persists.

If above SO answer has the same underlying issue (`any` value created in library, casted in executable, both with a definition) then this is tricky to fix since `Resumable::get` is a template over an open set which _needs to_ be declared in the header. I still tried to nudge the compiler to create the `stream::View` inside the `Resumable` to be created in the executable, but was unsuccessful here (which I think was expected).

Once #652 is merged I will check whether the problem disappears if one uses libc++ instead of libstdc++-8.3 (currently not possible as the LLVM libraries link against libstdc++).

**Comment by bbannier** [comment]
In any case, a workaround seems to be to use another standard library (debian-10 comes with `libstdc++-8.3`). I have tested that e.g., using `libc++` works.

**Comment by bbannier** [comment]
Unassigning myself as I am not sure how to make progress here.

**Comment by rsmmr** [comment]
Confirming that this is the problem from the SO posting: if I apply the patch mentioned in https://stackoverflow.com/a/52414724 to `any`, it works.

I don't see any work-around for this either. I think our only option is to swap in a different implementation for `any`. I think that would be reasonable thing to do as `any` is quite a standalone thing. A couple options from a quick search:

- https://github.com/kocienda/Any
- https://github.com/belegpp/belegpp-any/blob/master/beleg_any.h (super-minimal version)
- https://github.com/thelink2012/any

**Comment by bbannier** [comment]
Adding to that list, there is also a [`any` type in abseil](https://github.com/abseil/abseil-cpp/blob/master/absl/types/any.h) which is in general a well-maintained library. It also includes other tooling which might be useful (e.g., [`str_format`](https://abseil.io/docs/cpp/guides/format)).

**Comment by rsmmr** [comment]
I'm not a fan of large utility libraries. if we wanted to take that, we'd need to copy it out of there.

**Comment by bbannier** [comment]
> I'm not a fan of large utility libraries. if we wanted to take that, we'd need to copy it out of there.

I just checked, and the `absl::any` sublibrary only depends on their base library, so this should, at least after a short glance, be possible. We could build their library `STATIC` so we'd only need to take care of installing the needed header.

I believe even though they are bigger, there are also some benefits in using established utility libraries, namely they might potentially be optimized and tested more; medium term it might also be useful to be able use multiple utilities from a single library instead of having to integrate multiple libraries.
