### ISSUE TITLE
Investigate static analysis via lgtm.com

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#630]
We should check whether we can perform static analysis with lgtm.com. I added [Spicy](https://lgtm.com/projects/g/zeek/spicy/?mode=list), but this fails without a custom config.

I tried the following custom config:

```.yml
path_classifiers:
  library:
    - "3rdparty"

extraction:
  cpp:
    prepare:
      packages:
        - git
        - ninja-build
        - bison
        - flex
        - bison
        - llvm-9-dev
        - clang-9
        - libclang-9-dev
        - libc++1
        - libc++abi1
        - libc++abi-dev
        - curl
    after_prepare:
        - cd /usr/local/cmake && curl -L https://github.com/Kitware/CMake/releases/download/v3.15.0/cmake-3.15.0-Linux-x86_64.tar.gz | tar xzvf - -C /usr/local/cmake --strip-components 1
        - export PATH=/usr/local/cmake/bin:$PATH
        - export CXX=clang++-9
        - export CC=clang-9
        - export ASM=clang-9

    configure:
      command:
        - ./configure --generator=Ninja

    index:
      build_command:
        - ninja -C build
```

This installs a custom CMake, since with upstream package in lgtm's setup is too old. However, it seems that lgtm injects a custom cmake wrapper in order to capture build commands which is also too old (3.13.4). With that I believe we are blocked by lgtm bumping their CMake version, or by finding another way to produce the artifacts it expects.

```
[2020-12-16 15:22:33] [build] CMake Error at CMakeLists.txt:3 (cmake_minimum_required):
[2020-12-16 15:22:33] [build]   CMake 3.15.0 or higher is required.  You are running version 3.13.4
[2020-12-16 15:22:33] [build] -- Configuring incomplete, errors occurred!
```

**Comment by bbannier** [comment]
It looks like lgtm mainly integrates standard static analysis tools, possibly with improved diagnostics (e.g., pyright for Python, Clang Static Analysis for C++). With that we probably can accomplish much that it does without it. Static analysis via clang-tidy and pre-commit hooks is already part of the PR process.

Closing this for now.

**Comment by bbannier** [comment]
I look a little more into this and what I said above was not accurate. LGTM does not wrap clang-tidy, but uses [custom matchers](https://github.com/github/codeql/tree/main/cpp/ql/src) which are independent of e.g., clang-tidy. This could still be useful.

**Comment by rsmmr** [comment]
Ah, nice, I realize now that this is using GitHub's CodeQL. So yes, would be nice to get this run regularly.
