### ISSUE TITLE
Document properties that can be set at unit or module level (e.g., `%byte-order`)

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#638]
Document properties that can be set at unit or module level (e.g., `%byte-order`)

_Originally posted by @rsmmr in https://github.com/zeek/spicy/issues/441#issuecomment-662280370_

**Comment by rsmmr** [comment]
Closing because:

- Module-level properties are now documented through previous PR.
- Some unit-level properties will turn into attributes with #713 and be documented that way. The remaining unit-level properties pertain to specific use-cases and are already documented with them.
