### ISSUE TITLE
Single field unit destructuring.

### ISSUE THREAD

**Issue by mjsir911** [zeek/spicy#694]
Hello,

I have a use case where I have a unit with a single field that looks like this:
```
type Flag = unit(flag: bytes) {
	flag:	bytes &size=1 &requires=($$ == b" " || $$ == flag) &convert=($$ == flag);
};
```

When it is used I call it like `var: Flag(b"P")` but to access it I have to access the value through `var.flag`, which is a bit unfortunate because I only care about the `flag` value because it's the only value!

I'm repeating this pattern a lot because I have types with standard rules, eg:
```
type Alphanumeric = unit(size: uint64) {
	data:	bytes &size=size &requires=(!!$$.match(/[a-zA-Z0-9]+/)) &convert=($$.decode());
};
```

and typing `var: Alphanumeric(4)` is easier than copy-pasting `bytes &size=4 &requires=(!!$$.match(/[a-zA-Z0-9]+/)) &convert=($$.decode())`

Is there a way to either:
1) have a function return a type?
2) have a unit call return a type?

A suggestion to solving this would be to special-case the field name `self` because it doesn't make any sense anyways as a field name:
```
type Flag = unit(flag: bytes) {
	self:	bytes &size=1 &requires=($$ == b" " || $$ == flag) &convert=($$ == flag);
};
```

Would just result in `var` being the boolean

**Comment by rsmmr** [comment]
To make that little bit nicer, you could add a `&convert` to each `var`:

```
var: Flag &convert=$$.flag;
```

That way, `var` becomes the boolean, so at least access to it becomes easier.

I don't quite like special-casing `self` but how about this instead:

```
type Flag = unit(flag: bytes) {
	flag:	bytes &size=1 &requires=($$ == b" " || $$ == flag) &convert=($$ == flag);
} &convert=(self.flag); 
```

That would essentially add an implicit `&convert` to all usages of the type.

I'm also thinking to add "field declarations" to define shortcuts for more complex field types that are being used repeatedly, but not sure yet if that would help in this case (because of the unit parameter; field declarations probably won't support that).

**Comment by rsmmr** [comment]
Quick update here: after looking into this, it's a bit more involved to make it work consistently:  it should be transparent to the field using the unit whether there's a `&convert` or not; it should behave just like if the resulting value had been parsed directly. For example, there could be another `&convert` on the field itself, where it  should go into; or we could be parsing a vector. Making it all  work will take a little bit. I'm working on some cleanup of the parsing code already that should facilitate this, and I'm planing to integrate it there.

**Comment by mjsir911** [comment]
Thank you for the update @rsmmr, looking forward to it!

**Comment by rsmmr** [comment]
Setting milestone, I'm pretty close to have this working (I think :)
