### ISSUE TITLE
Zeek plugin: Provide access to parser for other side of the connection

### ISSUE THREAD

**Issue by rsmmr** [zeek/spicy#696]
Some Zeek analyzers need a way to correlate information across a connection's
two sides. To facilitate that, the unit that is parsing the originator side needs to
gain access to the unit parsing the responder side, and vice versa.

From a Spicy perspective, that's a bit tricky unfortunately because a Spicy
unit doesn't know anything about "the other side", especially not its unit type.
Because everything in Spicy is statically typed, we need to provide that
information somehow upfront somehow.

Here's one idea to implement this:

We could extend units with the concept of an external "context" object. A
host application (here: Zeek) would instantiate a context before kicking off
parsing and fill it with any information needed (e.g., the state for the
"other side"). Inside the unit needing access, we declare the type of the context 
object, and make it accessible through a new magic unit attribute, `__context__`. 

Possible syntax: A unit property `%context = T` will let `self.__context__` have a 
yield type of `optional<T&>`, with the optional remaining unset if the host application 
doesn't make a context object available.

Here's an example that gives to units access to each other, with each flagging for the
other when it's done:

```
public type Foo_Request = unit {
    %context = Foo_Request; 

    ...

    on %done {
        (*self.__context__).request_done = True;
    }

    var reply_done: bool;
};

public type Foo_Reply = unit {}
    %context = Foo_Request; 

    ...

    on %done {
        (*self.__context__).reply_done = True;
    }

    var request_done: bool;
};
```

Downside of all of this: Such a parser won't work with `spicy-driver` anymore because it wouldn't make the context available (maybe we could make it work in batch mode at least where we should be able to create the same context as the Zeek plugin).

**Comment by 0xxon** [comment]
This actually does look pretty great to me.

The fact that this does not work in spicy-driver also seems to be completely acceptable to me - as long as it is set to something like an empty unit.

**Comment by duffy-ocraven** [comment]
```
public type Foo_Request = unit {
    %context = Foo_Request; 
```
is a typo, right? The second line should say Foo_Reply

**Comment by rsmmr** [comment]
> is a typo, right? The second line should say Foo_Reply

yes, good catch.

**Comment by rsmmr** [comment]
I'm also mulling over a different syntax for this where one could customize the name of what is currently `__context__` to make it more meaningful. And maybe for Zeek, we'd use the pair of originator/responder units as the context, and then have both units use the same type. Something like:

```
type ZeekContext = tuple<orig: Foo_Request, resp: Foo_Reply>;

public type Foo_Request = unit {
    %context __zeek__ = ZeekContext; 

    ...

    on %done {
        (*self.__zeek__).resp.reply_done = True;
    }

    var reply_done: bool;
};

public type Foo_Reply = unit {}
    %context __zeek__ = ZeekContext; 

    ...

    on %done {
        (*self.__context__).orig.request_done = True;
    }

    var request_done: bool;
};
```

Not quite happy with this yet, something along those lines.

**Comment by rsmmr** [comment]
I ended up doing this slightly different, both for technical reasons but also because I believe that's a better approach that's more flexible and more readable. @0xxon take a look at #725 and see what you think.
