### ISSUE TITLE
Allow to add `&size` to a unit to limit its size

### ISSUE THREAD

**Issue by rsmmr** [zeek/spicy#700]
Example:

```
type bla = unit(total_len: uint64) {
a: uint16;
b: bytes size=self.a;
c: uint32;
d: uint8;
e: bytes &eod;
} &size = total_len;
```

**Comment by duffy-ocraven** [comment]
This would be used almost universally, in protocols that include the size of what follows, in their headers. My experience with &parse_from as a defensive programming technique against wild sizes/pointers in the data thereafter, is very similar. Before proceeding with this idea of &size attributes at the unit level, give a thought to whether it too should defend against wild sizes/pointers (and remember: enforce both ends--pointer addition can be negative) in the data thereafter.

**Comment by duffy-ocraven** [comment]
i just realized that your example set my mental-model into a superposition of two ideas. Is it your intention that &size attributes at the unit level indicate "the size of it must exactly be" or "the size that it is shall not exceed..."

**Comment by rsmmr** [comment]
it's "the size of it must exactly be": To the unit, it looks like end-of-data is reached at the `&size` limit, so it cannot pass beyond that (would be parse error if it tried). We then also check that all `&size` bytes have been consumed (if not, parse error again). These semantics are the same as if `&size` had been put on a field using the unit's type.

Not quite sure what that means for your original point. is there anything you'd like to see different?

**Comment by duffy-ocraven** [comment]
Your clarification affirmed my mental model for the other point I raised. So all-set here.
