### ISSUE TITLE
Add BinPAC-style pre-compilation to Zeek plugin

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#72]
Currently, the Zeek plugin always JITs the Spicy code. We need to support a different BinPAC-style mode as well: precompile everything into static C++ code, which is then compiled along with  the plugin itself, just as BinPAC does it.

**Comment by rsmmr** [comment]
This is now done by #502. Main difference to BinPAC is that we fully precompile the C++ code so that users don't need the Spicy toolchain installed.
