### ISSUE TITLE
Feature request: allow to jump forward in stream

### ISSUE THREAD

**Issue by 0xxon** [zeek/spicy#732]
Currently, set_input is only guaranteed to work when going backwards (see #727).

Especially for files it would be super neat if it would officially be supported to jump forwards (so - have spicy buffer the data till the point you want to jump to). I would also be happy if this would require a separate function call (so - something like ``self.buffer_input(number_of_bytes)`` to be guaranteed to work.

The work around of reading the data into a buffer first and then ``&parse``-ing that is not really workable in all cases - not all file types are nice enough to tell you at the beginning how much data you need to read to parse headers :)

**Comment by rsmmr** [comment]
Turns out it's working already!
