### ISSUE TITLE
Code-block for block in front of look-ahead operator is never executed

### ISSUE THREAD

**Issue by 0xxon** [zeek/spicy#736]
This:

```
module Test;

public type Testing = unit {
	:uint8[] {
		print "This is never raised";
	}
	: /ghi/ {
		print "This is";
	}
};
```

Leads to this output:
```
$ echo "abcdefghijklmno" | spicy-driver -d test2.spicy
This is
```

I would expect the first code block to either be executed - or if it is not possible to execute code blocks in these circumstances, for the parser to raise an exception telling you that this block is illegal at this place.

**Comment by rsmmr** [comment]
let's wait for #694 for this as the related code in the parser building is changing quite a bit with that.
