### ISSUE TITLE
Interaction between foreach and &while is undefined

### ISSUE THREAD

**Issue by 0xxon** [zeek/spicy#740]
I currently use the following pattern in a number of places:

```
type test = unit {
  var continue_parsing = True;
  element: subtype(self)[] &while(continue_parsing) foreach {
    if ( evaluate_something($$) ) {
      self.continue_parsing = False
    }
  }
};
```

It turns out that this works... most of the time. However, I just encountered the first case where, apparently, the content of foreach was executed after while was evaluated. This manifested in the vector trying to consume another element.

One can work around this by having a subtype like this:

```
type subtype = unit(top: test) {
  sub: actual_subtype if (top.continue_parsing);
}
```

which aborts when continue_parsing was actually already set to false. This is, however, actually not optimal.

To me this feels like a bug - I think foreach should always be executed before &while is evaluated.

I sadly don't have a small testcase. I have one case where this happens consistently for me - however that is with a rather long script and a test-file that is several megabytes large.

**Comment by rsmmr** [comment]
I can reproduce this. It does work with some other loop constructs, but `&while` and `foreach` seem to always execute in this order.
