### ISSUE TITLE
Allow Zeek file-analyzer replacement

### ISSUE THREAD

**Issue by jsiwek** [zeek/spicy#762]
Currently, `.evt` definitions allow use of `replaces ANALYZER_NAME` for substituting a Spicy *protocol* analyzer for builtin Zeek ones, but not for *file* (not sure if same applies for *packet*, but docs at least don't mention that as capability).

E.g. I started writing the Spicy-based PE parser/analyzer to be compatible w/ existing Zeek events, but can't currently override them via uncommenting:

https://github.com/zeek/spicy/compare/topic/jsiwek/pe#diff-ac6ed02b6e7206a11bf0f6be395839f99f9818ac20fc2d31d327903d9a503000R4

```
$ zeek -r ../../zeek/testing/btest/Traces/pe/pe.trace pe.spicy pe.evt zeek_pe.spicy pe.zeek test-pe.zeek
[error] /home/jon/pro/zeek/spicy/zeek/plugin/lib/file-formats/pe.evt:5: unexpect token
fatal error: error loading pe.evt: error loading EVT file "/home/jon/pro/zeek/spicy/zeek/plugin/lib/file-formats/pe.evt"
```

**Comment by rsmmr** [comment]
(Assigning jsiwek as he said he wants to give this a try.)
