### ISSUE TITLE
No way to constrain bytes/string parsing by both total length and null-termination

### ISSUE THREAD

**Issue by jsiwek** [zeek/spicy#767]
In context to what I described in https://github.com/zeek/spicy/discussions/765, I was looking for a way to constrain the parsing of null-terminated string by whether it reaches an arbitrary N-byte limit before seeing the null-terminator and this is one of the first ways I thought to try expressing that:

```
module Test;

public type NullTerminatedString = unit {
    s: bytes &size=4 &until=b"\x00";
};
```

```
$ printf 'testing\000' | spicy-dump test.spicy
[fatal error] terminating with uncaught exception of type spicy::rt::ParseError: parse error: end-of-data reached before &until expression found (test.spicy:4:8)
```

Not sure that's the expected/intuitive way for that to have failed, but is there ultimately some way to accomplish  "parse until a either a given byte-sequence is seen *or* an N-byte limit is reached", or can the combination of `&size` and `&until` be defined to have that meaning?

**Comment by rsmmr** [comment]
Seeing that this makes it through validation, I'm now wondering why it's not working; recalling the implementation, I think it should, so turning this into a bug.

That said, there's also the more generally point here of  potentially introducing something like a `&max-size` that would apply an upper-limit to the field's parsing (w/ parse error if exceeded). We could make that either `bytes` specific or, probably  better, apply to all fields: if parsing this field would require more than N bytes, bail out.

**Comment by bbannier** [comment]
The current implementation generates an `AND` which is not satisfied for the example input (for `testing\000` `\x00` is only seen for `size>7`). We generate the following HILTI code to parse `NullTerminatedString::s`,

```.ruby
local auto __until_bytes = b"\0";
local auto __until_bytes_sz = |__until_bytes|;
(*self).s = b"";

while ( True ) {
    spicy_rt::waitForInput(__data, __limited, __until_bytes_sz, "end-of-data reached before &until expression found", "/tmp/bla.spicy:4:12", (*self).__filters);
    local bool found;
    local iterator<stream> it;
    (found, it) = __limited.find(__until_bytes);
    (*self).s += __limited.sub(it);

    if ( found ) {
        __limited = __limited.advance(it + __until_bytes_sz);

        if ( __trim )
            (*__data).trim(begin(__limited));

        break;
    }
    else {
        __limited = __limited.advance(it);

        if ( __trim )
            (*__data).trim(begin(__limited));

    }
}
```

I am not sure what is the bug here @rsmmr. The current implementation includes the delimiter from `&until` in the enforced `&size`; this seems consistent to me, but one could also argue that it should be excluded.

Re: a potential `&max-size` attribute, an alternative with maybe wider usefulness to that could be to allow some form of `&until` taking a boolean, e.g., for @jsiwek's example,


```.ruby
public type NullTerminatedString = unit {
    s: bytes &parse_until=($$.match(some_re) || |$$| == 4);
};
```

This could only parse one byte at a time though so it might be hard to make efficient.

**Comment by bbannier** [comment]
My above comment isn't completely correct. If `&size` is present we set up a limited view into the input stream. From that limited view we extract data and e.g., apply `&until`. Above example then has the following post-conditions: (i) exactly `&size` bytes extracted, and (ii) the last byte to be extracted from the view ends in `&until`, but will not be included in the parsed result. This only holds for byte sequences of length 4 where all bytes but the last one are non-zero.

**Comment by bbannier** [comment]
The task here now would be to introduce a `&max-size` attribute. With that attribute present we would get parse semantics similar to `&size`, but not trigger a parse error if not all `&max-size` bytes were extracted. If parsing hasn't terminated once `&max-size` bytes have been extracted from the input stream a new parse error should be triggered.
