### ISSUE TITLE
Allow trailing comma in tuple type declarations

### ISSUE THREAD

**Issue by jsiwek** [zeek/spicy#772]
Not critical, but would find it convenient for some development/troubleshooting workflow where I was doing a lot of `tuple` type  member removal/re-arrangement if the syntax used for last element were more lenient (thinking about times when I was experimenting with how I wanted Zeek `record` types to look and having to update the Spicy `tuple` mapping):

```
module Test;

type MyTuple = tuple<
    bool,
    bool,
    >;
```
```
$ spicyc -j test.spicy
[error] test.spicy:6:5: syntax error, unexpected '>'
[error] spicyc: parse error
```

**Comment by rsmmr** [comment]
We did this for elements in tuple constructors already.
