### ISSUE TITLE
Allow &parse-at and &until combination

### ISSUE THREAD

**Issue by jsiwek** [zeek/spicy#773]
Wasn't clear why `&parse-at` and `&until` can't be combined in this example:

```
module Test;

public type MyUnit = unit {
    %random-access;

    a: bytes &size=4;
    b: bytes &parse-at=(self.start) &until=b"\x00";

    on %init { self.start = self.input(); }

    var start: iterator<stream>;
};
```
```
$ printf 'testing\000' | spicy-dump test.spicy
[error] test.spicy:7:5: attributes cannot be combined: &parse-at, &until
[error] spicy-dump: aborting after errors
```

It's a bit less convenient to workaround by making a separate `unit` like this:

```
module Test;

type NullTerminatedString = unit {
    s: bytes &until=b"\x00";
};

public type MyUnit = unit {
    %random-access;

    a: bytes &size=4;
    b: NullTerminatedString &parse-at=(self.start);

    on %init { self.start = self.input(); }

    var start: iterator<stream>;
};
```
```
$ printf 'testing\000' | spicy-dump test.spicy
Test::MyUnit {
  a: test
  b: Test::NullTerminatedString {
    s: testing
  }
  start: <expired>
}
```

The `spicy-dump` output also gets more verbose having to do it that way rather than have the null-terminated strings "inline" w/ the top `unit`.  Maybe same goes for other tools/output or even Spicy logic that then have to access fields via an extra `.` reference instead of directly.

**Comment by rsmmr** [comment]
With a bit of luck, this might just be an overzealous validator check that we can remove.
