### ISSUE TITLE
Zeek plugin is absent from binary package

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#794]
Testing on ubuntu-20 against the binary artifacts produced in the CI, the Zeek plugin does not seem to be part of the binary artifacts,

```
$ curl https://api.cirrus-ci.com/v1/artifact/github/zeek/spicy/docker_ubuntu20/packages/build/spicy-linux.tar.gz -o /tmp/spicy-linux.tar.gz
$ tar xf /tmp/spicy-linux.tar.gz
$ ./spicy-linux/bin/spicy-config --zeek-plugin-path
/opt/spicy/lib/spicy/Zeek_Spicy
$ ls /opt/spicy/lib/spicy/Zeek_Spicy
ls: cannot access '/opt/spicy/lib/spicy/Zeek_Spicy': No such file or directory
```

It seems none of the Zeek files are in the tarball.

**Comment by rsmmr** [comment]
Closing because the plugin is now split out into it's own repository and zkg will become the recommended way of installing.
