### ISSUE TITLE
Distribute Linux binary artifacts as deb or rpm files

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#815]
At least on Linux, we should distribute binary artifacts as distribution packages to make it easier to install and uninstall them.

**Comment by 0xxon** [comment]
Just as a random side-point - I wanted to note that, in principle, it should be possible to use the same distribution mechanism that we use for Zeek (so compile the project on OBS).

Doing that, it should be possible to just have dependencies on the Zeek packages that are built by OBS.

**Comment by rsmmr** [comment]
To collect the various ways of providing non-source builds, I'm thinking we should aim to provide the following for each release tag, plus master:

 - Debs/RPMs for our Docker platforms
        - Spicy only (`—build-zeek-plugin=no`)

  - Homebrew formula for Spicy 
        - Spicy only (`—build-zeek-plugin=no`)

  - Binary tgz or (DMG? ) for macOS Catalina + Big Sur
        - Spicy only (`—build-zeek-plugin=no`)

 
 - A single prebuilt Docker image 
        - Full install of Spicy + Zeek + Zeek plugin + Zeek analyzers
        - Use Zeek 4.0 for this

  - Dockerfiles:
        - Switch to installing only required dependencies (i.e., not Spicy)?
