### ISSUE TITLE
File analyzer tries to parse beyond end of file in some circumstances

### ISSUE THREAD

**Issue by 0xxon** [zeek/spicy#817]
When using a file analyzer in zeek, it tried to parse beyond the end of the file in some circumstances.

This behavior is currently exhibited for one file in the test-case of the PNG file analyzer. To reproduce - check out the ``topic/johanna/png`` branch of spicy-analyzers (or wait until https://github.com/zeek/spicy-analyzers/pull/5 is merged).

Then execute ``btest -t file/png.zeek`` in that repository. This will yield a weird.log containing:

```
#separator \x09
#set_separator	,
#empty_field	(empty)
#unset_field	-
#path	weird
#open	2021-03-04-14-57-51
#fields	ts	uid	id.orig_h	id.orig_p	id.resp_h	id.resp_p	name	addl	notice	peer	source
#types	time	string	addr	port	addr	port	string	string	bool	string	string
1258577885.355204	-	-	-	-	-	parse error: expecting 4 bytes for unpacking value (/Users/johanna/spicy/spicy-analyzers/analyzer/file/png/PNG.spicy:22:10)	FYdCSR32lxKYM7mSmk	F	zeek	-
#close	2021-03-04-14-57-51
```

When one extracts this file and runs it against spicy-driver manually, this error does not occur. Inspection of the file shows that there is no trailing data - parsing should just end.

The file is parsed using this construct:

```
: Chunk(self)[] &eod;
```

And I assume that, for some reason, parsing of the next chunk already starts, even though the file ends. The parsing error occurs while trying to parse the first element of Chunk.

**Comment by duffy-ocraven** [comment]
Doesn't that require double parentheses, as
```
: (Chunk(self))[] &eod;
```

**Comment by duffy-ocraven** [comment]
5.1.4. Unit Parameters section says:
```
... inside containers as well, though the syntax is a bit peculiar:

module Test;

type Bar = unit(mult: int8) {
    x: int8 &convert=($$ * mult);
    on %done { print self.x; }
};

public type Foo = unit {
    x: int8;
    y: (Bar(self.x))[]; # Element constructor must be in "(...)"
};
```
and 5.1.7.8 Vector section says:
`...requires special syntax are units with parameters. In that case, one needs to wrap the ELEM_TYPE in additional parentheses, and then add the parameters to it (e.g., x: (MyUnit("arg1"))[]).`

**Comment by 0xxon** [comment]
well, it works without them. I use that syntax quite excessively - and I am apparently lazy when typing.
