### ISSUE TITLE
using new in doc example leaks memory

### ISSUE THREAD

**Issue by duffy-ocraven** [zeek/spicy#840]
In https://docs.zeek.org/projects/spicy/en/latest/programming/parsing.html?highlight=subunit#unit-parameters
enhancing the code to illustrate the syntax and what is advocated, without a memory-leak (at: `msg = new s;`)
would be more appropriate.

**Comment by bbannier** [comment]
Could you point at exactly where this leaks? In the following Spicy code

```.r
global msg = new "foo";
```

`new "foo"` creates a strong reference which is bound to `msg`. I believe nothing should leak here.

Maybe you could show where you saw the leak in the generated code (`spicyc -c ...`).

**Comment by bbannier** [comment]
Closing this as I believe there is no issue here. Please reopen if I misunderstood the issue.

**Comment by duffy-ocraven** [comment]
memory-leak is at `msg = new s;`

which leaves the allocation from the prior call to new, now with nothing pointing to it.

**Comment by bbannier** [comment]
@duffy-ocraven, the language here is Spicy where `new` creates a referenced-counted value. Nothing should leak here.

**Comment by duffy-ocraven** [comment]
That distinction in the treatment of new in Spicy had escaped me. You are correct to close this. Nothing wrong using it that way in the doc example.
