### ISSUE TITLE
Support &size with switch

### ISSUE THREAD

**Issue by rsmmr** [zeek/spicy#844]
Would be useful to be able to add `&size` to a switch so that it applies to all cases:

```
switch ( x ) {
        0 -> a: ..;
        1 -> b: ..;
    } &size=5;
```

Right now one can work-around the lack of this by adding the same `&size` to each case. The OpenVPN analyzer does this, but it's cumbersome.

Should check if there are other attributes that would make sense to support in this way.

**Comment by bbannier** [comment]
This could probably be implemented by limiting the view the `switch` can see during parsing.
