### ISSUE TITLE
bitfield bug

### ISSUE THREAD

**Issue by jsiwek** [zeek/spicy#853]
When looking for an explanation for https://github.com/zeek/spicy-analyzers/issues/21, I found a platform-dependent difference in this associated parsing logic:

https://github.com/zeek/spicy-analyzers/blob/358904848246358097d90ece6bb2929bc1fa3098/analyzer/file/pe/pe.spicy#L376-L389

Think a minimal test case to reproduce looks like this:

```spicy
# test.spicy
module Test;

public type BF = unit {
    entry: bitfield(64) {
        full:         0..63;
    };
};
```

On an Ubuntu 20.04, GCC 9.3.0 system:

```
$ printf '\001\002\003\004\005\006\007\008' | spicy-dump test.spicy
Test::BF {
  entry: (full: 84281088)
}
```

On a macOS Big Sur 11.2.3, Apple Clang 12.0.0 system:

```
$ printf '\001\002\003\004\005\006\007\008' | spicy-dump test.spicy
Test::BF {
  entry: (full: 0)
}
```

That macOS result of `0` seems wrong.

**Comment by bbannier** [comment]
Thanks for the great reproducer @jsiwek.

The issue here can be reduced to the following inconsitency in the runtime library,

```.cpp
CHECK_EQ(hilti::rt::integer::bits(hilti::rt::integer::safe<uint64_t>(72623859790382848),
                                  hilti::rt::integer::safe<std::uint64_t>{0u},
                                  hilti::rt::integer::safe<std::uint64_t>{63u}, hilti::rt::integer::BitOrder::LSB0),
         84281088); // macOS
         // 0); // ubuntu

```

**Comment by bbannier** [comment]
Looking at the triggering C++ code it is clear that neither the OS X nor the Linux result is correct as one would expect to recover the input when extracting all bits.
