### ISSUE TITLE
CI race condition

### ISSUE THREAD

**Issue by rsmmr** [zeek/spicy#865]
Seems we have a problem now with CI for spicy-plugin/analyzers using binary builds of Spicy: when Spicy main is building while those CIs kick off, the package downloads don't work. And because master CI runs take a while to complete, that time window is actually pretty large. Seems the ideal solution would be storing the packages somewhere else and copying them over only once Spicy CI has finished; not sure how feasible that is.

**Comment by bbannier** [comment]
We usually don't see this, and I wonder whether the issue was triggered by #847 (unsure what that triggered inside Cirrus). Let's see if becomes a reoccurring issues.

**Comment by bbannier** [comment]
While a `main` `fedora32` CI task was running I just checked, and the packages from the previous `main` build were still accessible. With that I think we are fine here and what you saw was likely triggered by #847.

We still have a race where artifact from different CI tasks might be from different versions of `main`, but this seems unavoidable if we do not copy the files elsewhere once all jobs in a CI matrix are done.
