### ISSUE TITLE
Reject or sanitize NULL in input

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#872]
If users use `NULL` as a name in their Spicy input, we might emit `NULL` in the generated C++ code. This will likely collide with C's `NULL` macro.

We should either reject such names, or alternatively sanitize them.

**Comment by rsmmr** [comment]
`NULL` is already in the list of reserved words that the codegen shouldn't emit, see https://github.com/zeek/spicy/blob/c5b3923ac81d8b1ef8071e0b9ba3b2cd529ca2db/hilti/toolchain/src/compiler/cxx/elements.cc#L26 . Need to track down where that goes wrong here.

**Comment by bbannier** [comment]
If I recall correctly this was seen by in the context of enums. Made up reproducer:

```.r
module N;

type E = enum {
    NULL = 0
};

type X = unit {
    e: uint8 &convert=E($$);
    switch (self.e) {
        E::NULL -> x : void;
    };
};
```
