### ISSUE TITLE
`&convert` issue with unit parameters

### ISSUE THREAD

**Issue by rsmmr** [zeek/spicy#917]
```
module Test;

import spicy;

type Foo = unit(len: uint64) { } &convert="foo";

type Bar = unit {
  x: Foo(42);
};
```

```
# spicyc -j test.foo
/private/var/folders/zw/k8p4sh6n1m915kvmp6w6jzpw0000gp/T/hilti-rt-test-xLiH23/Test.cc:150:58: error: no matching conversion for functional-style cast from 'hilti::rt::integer::safe<std::uint64_t>' (aka 'SafeInt<unsigned long long, detail::SafeIntException>') to 'std::string' (aka 'basic_string<char>')
        hilti::rt::optional::valueOrInit((*__self).x) = (std::string(hilti::rt::integer::safe<std::uint64_t>{42u}));
[...]
```

Oddly enough, this works without the unit parameter at the call site (i.e., `x: Foo` instead of `x: Foo(42)`), by either removing the parameter from the type as well or defaulting it to something.

**Comment by bbannier** [comment]
This issue is cause by the way we currently generate default value for fields here, https://github.com/zeek/spicy/blob/8e2937b6fcfe906351f1c8b311a2a58568b93c50/spicy/toolchain/src/compiler/codegen/parser-builder.cc#L427-L429.
