### ISSUE TITLE
implement bitwise shift left and right (<< and >>) operators for bytes

### ISSUE THREAD

**Issue by mmguero** [zeek/spicy#921]
In creating an updated ASN.1 parser (see zeek/spicy-analyzers#56), I left the ASN.1 BitString type unimplemented, the reason being [this comment from @0xxon](https://github.com/rsmmr/hilti/blob/master/libspicy/parsers/asn1.spicy#L81) in the original ASN.1 hilti/spicy example from 2016:

```
 # we need >> and << for bytes before we can implement complex bitstrings. I don't think that is here yet.
```

Reviewing the documentation on [`bytes`](https://docs.zeek.org/projects/spicy/en/latest/programming/language/types.html#bytes) I don't see that it's been added yet. Creating this ticket so I can reference it in that comment in the ASN.1 unit.

**Comment by rsmmr** [comment]
Mind elaborating the semantics of what `<<`/`>>` should be doing when applied to `bytes`? Doesn't seem immediately intuitive to me.

**Comment by mmguero** [comment]
Honestly I don't know, @bbannier commented on the code review of zeek/spicy-analyzers#56 that I should capture that comment by @0xxon in the original asn1.spicy as an issue here on github. What I'm using the ASN.1 stuff for doesn't seem to make use of the constructed bitstring so I haven't taken the time to figure out what he meant there.

I'm happy to just leave that as a TODO in my unit to be tackled later by someone who needs it.

**Comment by rsmmr** [comment]
I'm going to close this until we have a better understanding of the use case.
