### ISSUE TITLE
We don't support --enable-sanitizer on macOS yet

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#94]
We don't even fail nicely. See !35 for how that looks like.

**Comment by rsmmr** [comment]
@bbannier Is this stil true?

**Comment by bbannier** [comment]
This seems to largely work. If I configure with `--enable-sanitizer` on macos, sanitizer-related flags are injected and propagated. Unit tests pass. When directly executing `btest` a number of tests still fail:

- `hilti.hiltic.cc.leak` and `hilti.hiltic.jit.leak` fail since at least on my machine leak checking is disabled. Modifying the tests to have `ASAN_OPTIONS=detect_leaks=1` on the invocations lets them pass. Alternatively this could also be added to the `btest.cfg` (not sure how other tests behave with that).

- a large number of Zeek-related tests fail since the Zeek invocation is not correct.

```==72730==ERROR: Interceptors are not working. This may be because AddressSanitizer is loaded too late (e.g. via dlopen). Please launch the executable with:
DYLD_INSERT_LIBRARIES=/usr/local/opt/llvm/lib/clang/11.0.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib
"interceptors not installed" && 0/Users/bbannier/src/spicy/tests/Scripts/run-zeek: line 8: 72730 Abort trap: 6           LD_PRELOAD=${ZEEK_LD_PRELOAD} ASAN_OPTIONS=detect_leaks=0:detect_odr_violation=0 ${zeek} $@
```

This affects the following tests:

`zeek.evt.file-analyzer`
`zeek.evt.list-conversion`
`zeek.evt.export-enum`
`zeek.evt.multiple-enum`
`zeek.evt.file-analyzer-property`
`zeek.evt.import-from`
`zeek.evt.double-types`
`zeek.evt.tuple-arg`
`zeek.evt.double-event`
`zeek.evt.event-cond`
`zeek.evt.replaces`
`zeek.evt.tuple-enum`
`zeek.evt.type-converter`
`zeek.evt.udp`
`zeek.evt.module-path`
`zeek.evt.optional`
`zeek.evt.ssh-banner`
`zeek.lib.protocols.tftp`
`zeek.lib.protocols.dns`
`zeek.lib.protocols.http`
`zeek.lib.protocols.dhcp`

I suspect they only really works with `ci/run-ci` on any platform which sets up the correct `ZEEK_LD_PRELOAD`.
