### ISSUE TITLE
Issues with source tar ball

### ISSUE THREAD

**Issue by rsmmr** [zeek/spicy#943]
Our release tgz of the source code (`spicy.tar.gz`)has a couple of issues:

- It doesn't have a top-level `spicy` directory, unpacks directly into the current directory. It should unpack into `spicy-<version>/`.

- When building it reports:

```
/Users/robin/tmp/x/scripts/autogen-version --header /Users/robin/tmp/x/build/include/hilti/rt/autogen/version.h --git-root /Users/robin/tmp/x
Traceback (most recent call last):
  File "/Users/robin/tmp/x/scripts/autogen-version", line 155, in <module>
    major, minor, patch, *_ = version.split(".")
ValueError: not enough values to unpack (expected at least 3, got 1)
[16/338] Building CXX object 3rdparty/benchmark/src/CMakeFiles/benchmark.dir/benchmark_register.cc.o
ninja: build stopped: subcommand failed.
```

**Comment by bbannier** [comment]
Hmm, this passes for me locally and also in CI. Could you post the `./configure` line you used? At the point the only hunch I have is that this might be due some race in our CMake setup where we add sublibrary version targets before we have computed the global `VERSION` file.
